### ISSUE TITLE
Feature request: follow symbolic links

### ISSUE THREAD

**Issue by mete888** [hasse69/rar2fs#46] opened 2016-03-04 13:17 UTC
rar2fs currently doesn't follow symbolic links.
Symlinced folders which contains rar files are presented as rar files.

Is there a chance to get symbolic links followed?

Thanks

**Comment by hasse69** [comment] 2016-03-04 16:58
This is a duplicate of issue #15

**Closed** 2016-03-04 16:58 UTC
Labels: Duplicate
