### ISSUE TITLE
Local cache

### ISSUE THREAD

**Issue by braderhart** [hasse69/rar2fs#135] opened 2020-03-16 11:14 UTC
Is it possible to save and re-utilize a cache across mounts that tracks files to help speed up initial mounts? A use case would be when the RAR files don't change, but the only thing that may change is the path or files/directories being removed. I understand this wouldn't be helpful in all situations, but could definitely speed up operations for some.

**Comment by hasse69** [comment] 2020-03-19 16:04
The idea has popped up many times, and every time it is dropped after some deeper analysis.
It would be very hard to make such a non-volatile cache to work flawlessly and also the increased logic and design complexity it would require does not motivate such a huge undertaking.
There are other things you can do to speed up the process significantly after a mount.
Use a low value (as low as possible without loosing data) for `--seek-length` and use the new `warmup` mount option. The cache warm-up will basically start automatically in the background at mount time and populates the entire directory cache. Note that there are not just one cache but two implemented by rar2fs. One for directories lists and one for actual file properties. Those two variants serve very different purposes but they complement each other.

**Comment by karibertils** [comment] 2020-04-08 16:33
RocksDB would probably be useful to implement this.

**Comment by hasse69** [comment] 2020-04-13 17:47
@karibertils thanks for the pointer, but as things stand right now there will be no effort made to save data in some persistent storage.

**Comment by hasse69** [comment] 2020-04-13 18:16
@braderhart Unless there is something more that you wish to add I would like to close this issue.

**Comment by braderhart** [comment] 2020-04-14 03:44
@hasse69 Thanks for checking in before you close the issue. I'm looking forward to the warm-up option. Unfortunately I think a lot of release groups still utilize RAR files for distribution, and due to that there are going to be limited options for performance. Maybe the ideal solution is to just unpackage and store in unarchived format. I understand your position on the matter, but I do believe there is a significant interest in exploring all options to make these RAR video files work at near-native speed.

**Comment by hasse69** [comment] 2020-04-14 05:41
@braderhart The `warmup` mount option was added in v1.29.0 so it is already available.
AFAIK the use-case you are referring to also in the majority of the cases implies archive volumes for which there is only a single file. In that case use the `--seek-lenght=1` option to speed up meta-data lookup. 

But there is still something that I fail to understand here. Extraction speed has nothing to do with the cache really. Extraction speed itself is not that much worse than using a native file on a local file system, with the exception of the possible overhead caused by FUSE itself or if the file is compressed in which you need to face the overhead of unpacking. But for streaming data you would probably not even notice the difference? A recursive mount point lookup (e.g. `ls -R`) might be a bit painful for huge collections but if you know what path to search it would not cause much overhead, if any.

**Comment by braderhart** [comment] 2020-04-15 23:44
I am already using the `--seek-length=1` option and it does help quite a bit. When mounting via rclone and then using a rar2fs mount on top of that, it is taking about 20+ secs to list a directory with an uncompressed multi-part RAR. However, it takes less 3 seconds using rclone mount to list the files.

It is possible that I have something mis-configured causing additional delay, but in the meantime I'll try the latest version.

**Comment by hasse69** [comment] 2020-04-16 09:24
That sounds really bad? Can you tell if the size of the individual RAR archive volume affects the time it takes? You could create a volumed test archive with very small sets.

As I have stated before, only headers are read in order to access file names etc. inside an archive. For volumes we need to in fact always read two volumes due to technical reasons. But the amount of data needed from each volume file should be in the size of bytes, not even kilobytes.
Could it be so that `rsync` does not handle this very well and tries to download the entire file first before rar2fs gets a chance to open it? Then things would become depending entirely on your network speed, I would bet you that if you put that archive on some local files system and mounted it using rar2fs it would not become close to even a second to populate the directory entry when using `--seek-length=1`.

**Comment by hasse69** [comment] 2020-04-22 20:11
Any updates here?

**Comment by hasse69** [comment] 2020-05-10 19:24
Closing this due to inactivity.

**Closed by hasse69** 2020-05-10 19:24 UTC
