### ISSUE TITLE
Plex media inaccessible. Permission issue.

### ISSUE THREAD

**Issue by Marabon** [hasse69/rar2fs#111] opened 2019-08-08 02:13 UTC
Hey,

I've looked around and haven't figured it out, I've seen a few issues that's somewhat similar but figured I'd open this, sorry if I missed something obvious.

So, recently I noticed my media being flagged as inaccessible, and when looking at the mounted drive/files I do see the .mkv file having the permissions "Special Permissions", unlike the other files (in the same directory), which have "Read" permission.

I'll attach a couple of screenshots:
https://i.imgur.com/xq2OCdc.png (Plex inaccessible, how I first noticed)
https://i.imgur.com/5KLiCZc.png (.nfo file properly has Read access)
https://i.imgur.com/vYcSbWZ.png (.mkv in the same directory, doesn't have Read)

Not sure why it's doing this as it seems to only be some .mkv files, not all of my library.

Thanks in advance for any suggestions you can give as to how to resolve it.

EDIT: Both source and mount are on the same system. As well as the Plex server. The file has correct permissions (Read) in the source directory.
The file plays fine in VLC while still rared from source, but fails when trying to play from the mount for obvious permission reasons.

**Comment by hasse69** [comment] 2019-08-08 07:51
Thanks for the issue report.
First of all, I need to understand a bit more about the problem.
Have these problematic files suddenly stopped working or have they always obtained these strange permission bits? I can see from the screenshots you are accessing the files from Windows, so is this a Samba/CIFS mount or are you using some Windows/FUSE layer such as Dokany or WinFSP?
Also, what version of rar2fs are you using and what mount options do you use?
In any case, have you tried to enter the mount point directly from the console or a shell and listed the files from there? What are the permissions if you do it directly like that and not through the Windows explorer?

**Comment by Marabon** [comment] 2019-08-08 13:24
I'm not entirely sure if it just happened, or if they've been doing it all along. I haven't changed anything since before I noticed it so I'm assuming it's been all along. However some of the files have been downloaded after I noticed it, so that makes it a bit weird.

I'm running cygwin and WinFSP with rar2fs v1.27.2. WinFsp-FUSE v2.8.

I have tried looking at the permissions of the 2 files in the terminal:
https://i.imgur.com/wZNUpDQ.png (mount drive)
https://i.imgur.com/DN9OMVJ.png (source drive, rared)
https://i.imgur.com/dORZJYc.png (source drive, unrared and renamed (added 2) to have both files in mount)
https://i.imgur.com/7GV0Apm.png (mounted drive, with both rared .mkv and unrared .mkv showing)

Hope this helps, let me know if you need more information.

**Comment by hasse69** [comment] 2019-08-08 13:49
I think I need access to one of the problematic archives to be able to try figure out what is going on here. You can mail me the details on how to obtain it to hans.beckerus AT gmail.com.

**Comment by Marabon** [comment] 2019-08-08 14:07
Email sent.

That makes sense with the permissions, is there any way to make rar2fs set some kind of default permissions if what's stored is missing?

Working files advanced permissions: https://i.imgur.com/lNRkOUr.png
Rared not working files advanced permissions: https://i.imgur.com/T0AN7EM.png

I'm guessing it's the Read data or Execute file permission that's missing.

**Comment by hasse69** [comment] 2019-08-08 14:16
I think we can try something here and now,
in rar2fs.c at line 2077                  
```
mode = (mode & ~S_IFMT) | S_IFREG;
```
Replace with
```
mode = (mode & ~S_IFMT) | S_IFREG;
if (mode == S_IFREG)
        mode |= (0666 & ~umask_);
```

**Comment by Marabon** [comment] 2019-08-08 14:29
Thanks, I had to leave home, but I'll try this when I get back and report if it works or fails.
Fingers crossed it works, would be nice to have those archives working.

**Comment by hasse69** [comment] 2019-08-08 14:30
I will try your archive later too, maybe I can reproduce the issue and come up with a better solution.

**Comment by hasse69** [comment] 2019-08-08 15:58
Also, you can check if the FUSE `umask` mount option is something that works for you, e.g. `-o umask=022`. Be aware though that this option works a little bit differently than the traditional umask. It basically applies all bits (ignoring whatever the file system implementation sets) and then masks those specified, meaning bits are set the same for directories and regular files, which obviously is not optimal.

**Comment by hasse69** [comment] 2019-08-08 18:24
I did a feeble attempt to reproduce your problem, but unfortunately under Linux is works just fine.
The mode bits as stored in the archive are 0600 octal, which mean read+write for owner.
I need you to dump the mode bits as you read them under Cygwin for me (I have no such environment available right now).
Before line 2077, add this
```
printf("mode = %4o\n", mode & ~S_IFMT);
```
Then run rar2fs with the -f flags to start in foreground and list the directory in question.
You should see the printout in the Cygwin console.
From Linux is looks like this:
```
total 809780
-rw------- 1 hasse hasse 829206192 Jul 25 01:53 suits.s09e02.720p.web.x264-tbs.mkv
-rwxr-xr-x 1 root  root         42 Aug  8 19:14 suits.s09e02.720p.web.x264-tbs.nfo
-rwxr-xr-x 1 root  root        765 Aug  8 19:14 suits.s09e02.720p.web.x264-tbs.sfv
```
So either rar2fs fails to properly read the bits or Cygwin/WinWSP handles the reported differently than on legacy Linux.

**Comment by hasse69** [comment] 2019-08-08 18:38
Ok, even under Cygwin I manged to get everything to look the same
```
$ uname -a
CYGWIN_NT-10.0 Host 2.11.0(0.329/5/3) 2018-08-31 13:05 x86_64 Cygwin
$ ls -l
total 809774
-rw------- 1 Hasse None 829206192 Jul 25 01:53 suits.s09e02.720p.web.x264-tbs.mkv
-rwxr----- 1 Hasse None        42 Aug  8 19:14 suits.s09e02.720p.web.x264-tbs.nfo
-rwxr----- 1 Hasse None       765 Aug  8 19:15 suits.s09e02.720p.web.x264-tbs.sfv
```
So, I cannot seem to reproduce what you see I am afraid :(

**Comment by Marabon** [comment] 2019-08-08 19:09
I haven't had time to try out the things you've suggested yet, will probably be able to try it later though.

That winfsp version is the exact same I used.
I think most if not all of the files that's been having these issues have been -TBS releases though. I'm not 100% sure it's just them, but I know those are the ones I've seen the most.
It's just weird that it's not ALL of their releases, which would make troubleshooting a lot easier.

I'll report back with the results of the above tests once I got them.

**Comment by hasse69** [comment] 2019-08-08 19:19
Well, the funny thing here is that it works just fine for me.
So I would expect you to see the same as I do :(

**Comment by Marabon** [comment] 2019-08-08 19:26
I've found another archive that shows the same as the one I've already mentioned, this one is on another physical drive though, but it's -TBS again.

Not sure how you'd like to proceed, something is clearly wonky :(
Could it be because of the different Cygwin release?
Would be helpful if someone else had the problem as well, so we have at least one more person than just me having the issue and you being unable to reproduce it.

**Comment by hasse69** [comment] 2019-08-08 19:28
Now using
```
CYGWIN_NT-10.0 Host 3.0.7(0.338/5/3) 2019-04-30 18:08 x86_64 Cygwin
```
Still works fine. 
I think you need to add the printout so that we at least can confirm that rar2fs at least behaves the same. It is huge software stack involved so there are many things that can go wrong.

**Comment by hasse69** [comment] 2019-08-08 19:32
Another question is, which version of unrarsrc are you using? I am using unrarsrc-5.6.5.tar.gz.

**Comment by hasse69** [comment] 2019-08-08 19:37
Tried latest from rarlabs, works fine.
```
$ ./rar2fs.exe -V
rar2fs v1.27.2-gitc572847 (DLL version 8)    Copyright (C) 2009 Hans Beckerus
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under
certain conditions; see <http://www.gnu.org/licenses/> for details.
WinFsp-FUSE version 2.8
```

**Comment by Marabon** [comment] 2019-08-08 19:44
unrarsrc-5.7.3

$ ./rar2fs.exe -V
rar2fs v1.27.2 (DLL version 8)    Copyright (C) 2009 Hans Beckerus
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under
certain conditions; see <http://www.gnu.org/licenses/> for details.
WinFsp-FUSE version 2.8

**Comment by hasse69** [comment] 2019-08-08 19:50
Just to make sure, can you also try this
```
$ ldd.exe ./rar2fs.exe
        ntdll.dll => /cygdrive/c/WINDOWS/SYSTEM32/ntdll.dll (0x7ffcb3b80000)
        KERNEL32.DLL => /cygdrive/c/WINDOWS/System32/KERNEL32.DLL (0x7ffcb2c80000)
        KERNELBASE.dll => /cygdrive/c/WINDOWS/System32/KERNELBASE.dll (0x7ffcb0d10000)
        cygfuse-2.8.dll => /usr/bin/cygfuse-2.8.dll (0x529650000)
        cygwin1.dll => /usr/bin/cygwin1.dll (0x180040000)
        cygstdc++-6.dll => /usr/bin/cygstdc++-6.dll (0x3fe670000)
        cyggcc_s-seh-1.dll => /usr/bin/cyggcc_s-seh-1.dll (0x3ff8d0000)
```

**Comment by Marabon** [comment] 2019-08-08 19:52
$ ldd.exe ./rar2fs.exe
        ntdll.dll => /cygdrive/c/WINDOWS/SYSTEM32/ntdll.dll (0x7ffbd5d20000)
        KERNEL32.DLL => /cygdrive/c/WINDOWS/System32/KERNEL32.DLL (0x7ffbd5930000)
        KERNELBASE.dll => /cygdrive/c/WINDOWS/System32/KERNELBASE.dll (0x7ffbd2060000)
        cyggcc_s-seh-1.dll => /usr/bin/cyggcc_s-seh-1.dll (0x3ff570000)
        cygfuse-2.8.dll => /usr/bin/cygfuse-2.8.dll (0x4d8220000)
        cygstdc++-6.dll => /usr/bin/cygstdc++-6.dll (0x3fe340000)
        ??? => ??? (0xe40000)
        cygwin1.dll => /usr/bin/cygwin1.dll (0x180040000)
        ??? => ??? (0xe40000)
        ??? => ??? (0xe40000)

**Comment by hasse69** [comment] 2019-08-08 19:58
Looks good (never mind the ???, its a "feature" in ldd).
Ok, we are back to needing that printout/trace from your side.

**Comment by Marabon** [comment] 2019-08-08 20:33
```
$ rar2fs -f /cygdrive/e/TV\ A-L/12\ Monkeys/12.Monkeys.S04E06.720p.WEB.x264-TBS/ O:
rar2fs: PID 54744: mounted O:
The service rar2fs has been started.
mode =  600
```

```
total 844516
---------- 1 x x 864775589 Jun 23  2018 12.monkeys.s04e06.720p.web.x264-tbs.mkv
-rwxrwxr-x 1 x x        47 Jul 25  2018 12.monkeys.s04e06.720p.web.x264-tbs.nfo
-rwxrwxr-x 1 x x       900 Jul 25  2018 12.monkeys.s04e06.720p.web.x264-tbs.sfv
```

**Comment by hasse69** [comment] 2019-08-08 20:40
Well then,, we just confirmed the permission mode bits as read from the archive is fine.
So something is then making those bits vanish...
The only thing I can think of right now is your currently active umask, can you check that?

**Comment by Marabon** [comment] 2019-08-08 20:41
```
$ umask
0022
```

**Comment by hasse69** [comment] 2019-08-08 20:49
Ok, then I have no clue I am afraid :(
I cannot see any reason why the same output from rar2fs would show up differently on your system than on mine. Please try the other workaround, adding `-o umask=000` to the mount options.
I am not really sure this is an issue with rar2fs to be honest.

**Comment by Marabon** [comment] 2019-08-08 20:56
```
$ rar2fs -f /cygdrive/e/TV\ A-L/12\ Monkeys/12.Monkeys.S04E06.720p.WEB.x264-TBS/ O: -o uid=000
rar2fs: PID 54760: mounted O:
The service rar2fs has been started.
mode =  600
```

```
$ ls -l
total 844516
-rw------- 1 Unknown+User x 864775589 Jun 23  2018 12.monkeys.s04e06.720p.web.x264-tbs.mkv
-rwxrwxr-x 1 Unknown+User x        47 Jul 25  2018 12.monkeys.s04e06.720p.web.x264-tbs.nfo
-rwxrwxr-x 1 Unknown+User x       900 Jul 25  2018 12.monkeys.s04e06.720p.web.x264-tbs.sfv
```

```
$ stat /cygdrive/o/12.monkeys.s04e06.720p.web.x264-tbs.mkv
  File: /cygdrive/o/12.monkeys.s04e06.720p.web.x264-tbs.mkv
  Size: 864775589       Blocks: 844508     IO Block: 65536  regular file
Device: bfb1559ch/3216070044d   Inode: 7743262778922486871  Links: 1
Access: (0600/-rw-------)  Uid: (4294967295/Unknown+User)   Gid: (197609/   chris)
Access: 2018-06-23 11:49:38.000000000 +0200
Modify: 2018-06-23 11:49:38.000000000 +0200
Change: 2018-06-23 11:49:38.000000000 +0200
 Birth: -
```

I'm not sure either where the error is, I just know there is something in between the physical drive and the mounted unrar'ed file :)
It's very odd.

**Comment by hasse69** [comment] 2019-08-08 21:03
If you remove the umask option and only `stat` the drive, what do you see as permission for the drive itself? E.g.
```
$ stat /cygdrive/d
  File: /cygdrive/d
  Size: 0               Blocks: 12         IO Block: 65536  directory
Device: f008a741h/4027098945d   Inode: 1407374883553285  Links: 1
Access: (0770/drwxrwx---)  Uid: (  544/Administrators)   Gid: (   18/  SYSTEM)
Access: 2019-08-08 20:26:11.559319800 +0200
Modify: 2019-08-08 20:26:11.559319800 +0200
Change: 2019-08-08 20:26:11.559319800 +0200
 Birth: 2007-05-19 10:02:20.078125000 +0200
```
Also, if you mount to a local folder, does it behave the same?

**Comment by Marabon** [comment] 2019-08-08 21:10
I'm seeing my user in cygwin as Uid and Gid.

This is stat of the drive without -o umask
```
$ stat /cygdrive/o
  File: /cygdrive/o
  Size: 0               Blocks: 0          IO Block: 65536  directory
Device: bfb1559ch/3216070044d   Inode: 1407374883687339  Links: 1
Access: (0775/drwxrwxr-x)  Uid: (197609/   x)   Gid: (197609/   x)
Access: 2018-07-25 00:30:53.132912800 +0200
Modify: 2018-07-25 00:30:53.132912800 +0200
Change: 2018-07-25 00:30:53.132912800 +0200
 Birth: 2018-07-25 00:29:11.174502500 +0200
```

and this is mounting locally in cygwin without umask:
```
$ ls -l
total 844516
---------- 1 x x 864775589 Jun 23  2018 12.monkeys.s04e06.720p.web.x264-tbs.mkv
-rwxrwxr-x 1 x x        47 Jul 25  2018 12.monkeys.s04e06.720p.web.x264-tbs.nfo
-rwxrwxr-x 1 x x       900 Jul 25  2018 12.monkeys.s04e06.720p.web.x264-tbs.sfv
```

**Comment by hasse69** [comment] 2019-08-08 21:20
Alright. The funny thing here is why you seem to get a proper UID/GID for you mount point while I am not. I get the strange `no+body` user/group. Something is different in our system setup, but I cannot answer to what that could be. Anyways, probably not even related. Since it does not seem to work even for a local folder mount it is not some permission inheritance involved from what I can tell at least. I think I will have to let you down on this one :( Not something I tend to tell people very often but in this case I am clueless to what is going on. But the good news is that you seem to have a viable workaround at least, the `umask` mount option. I hope this is enough for you to continue, Unfortunately not the answer I would have liked to give you. If I suddenly (for some reason) can think of something else, maybe I can let you know so that you can try it out.

**Comment by Marabon** [comment] 2019-08-08 21:23
Yeah, as long as the workaround works for me it's all good.

Just a shame to not get to the bottom of it.
The only thing that I think was differing on our systems was the unrarsrc version whereas I'm on unrarsrc-5.7.3.tar.gz and you were on unrarsrc-5.6.5.tar.gz.
I tried to see if I could find any changelog with major changes between those versions but I can't seem to find any.

Again, much appreciated you taking the time to look into it. It'd probably be helpful if I wasn't the only one with the issue though. :)

**Comment by hasse69** [comment] 2019-08-08 21:27
I have tried both latest version and your specific version of unrarsrc, and the result is the same for me. The access mode looks ok.

**Comment by Marabon** [comment] 2019-08-08 21:33
Yeah, makes sense. I'd have preferred to find a proper fix/solution though rather than a workaround, not only for me but for future issues and to make things better. :) 👍

**Comment by hasse69** [comment] 2019-08-08 21:49
This issue triggered me to consider a new option to rar2fs (`--no-inherit-mode`) that can change the default behavior and instead of applying access mode bits from the archive, instead apply standard access masked using current active umask. But now I am a bit worried that in your case such an option would still not help since we could see 0600 being read from the archive but still it was not populated properly to the upper layers. So can we check one more thing, the printout you added was *before* umask was applied, right? Maybe the umask rar2fs picked up is wrong for some reason? Can you add the same printout of `mode` also after this line (if not already):
``´
                        mode = (mode & ~S_IFMT) | S_IFREG;
```

**Comment by Marabon** [comment] 2019-08-08 22:02
This is with the print before and after
```
$ rar2fs -f /cygdrive/e/TV\ A-L/12\ Monkeys/12.Monkeys.S04E06.720p.WEB.x264-TBS/ O:
rar2fs: PID 58677: mounted O:
The service rar2fs has been started.
mode =  600
mode =  600
```

Compiling the last part now as I saw it after compiling the first changes.

**Comment by hasse69** [comment] 2019-08-08 22:20
This is so weird! So setting mode to 0600 (as code did originally) yields a completely empty access mode field! But setting the mode to 0644 by brute force, suddenly yields read access to *everyone*!?
The mode 0644 should have resulted in -rw-r--r--. So how come suddenly the read bit is propagated for the owner but not if you give it 0600. Its magic to say the least...what am I missing here?

**Comment by Marabon** [comment] 2019-08-08 23:39
```
$ rar2fs -f /cygdrive/e/TV\ A-L/12\ Monkeys/12.Monkeys.S04E06.720p.WEB.x264-TBS/ O: -o uid=-1,gid=-1
rar2fs: PID 62579: mounted O:
The service rar2fs has been started.
mode =  600
mode =  644
```

```
$ ls -l
total 844516
-r--r--r-- 1 x x 864775589 Jun 23  2018 12.monkeys.s04e06.720p.web.x264-tbs.mkv
-rwxrwxr-x 1 x x        47 Jul 25  2018 12.monkeys.s04e06.720p.web.x264-tbs.nfo
-rwxrwxr-x 1 x x       900 Jul 25  2018 12.monkeys.s04e06.720p.web.x264-tbs.sfv
```

**Comment by hasse69** [comment] 2019-08-09 06:32
Here is something else I need you to try
Replace line 1740
```´
#if !defined ( DEBUG_ ) || DEBUG_ < 5
```
with
``´
#if 0
```
You will now see a few extra things dumped in the terminal.
Keep a watch on the printout that comes as a result of doing `ls -l` on the file.
I need to confirm if the mode bits are leaving rar2fs correctly or if they were corrupted on the way.

**Comment by Marabon** [comment] 2019-08-09 16:58
This is the first occurrence matching the size of the file
```
struct stat {
    st_dev = 0
   st_mode = 100644 (octal)
  st_nlink = 1
    st_ino = 0
    st_uid = 197609
    st_gid = 197609
   st_rdev = 0
   st_size = 864775589
 st_blocks = 1689016
st_blksize = 0
}
```
This is the last occurrence matching the size 
```
struct stat {
    st_dev = 0
   st_mode = 100644 (octal)
  st_nlink = 1
    st_ino = 0
    st_uid = 197609
    st_gid = 197609
   st_rdev = 0
   st_size = 864775589
 st_blocks = 1689016
st_blksize = 0
}
```

Note that this is with the previous change to 2078, should I have reversed that change?
`mode = (0666 & ~umask_) | S_IFREG;`

**Comment by hasse69** [comment] 2019-08-09 17:15
Just for clarity it would be good to revert the first change, yes.
But, judging from what I see already here is that the bug is definitely not in rar2fs.
The last printout is at the point in which file stats are reported to the FUSE layer.
In this case that would be the WinFSP/FUSE emulation layer. So right now everything is pointing to the problem lying somewhere else. I think you might need to file an issue report towards WinFSP/FUSE which is the next level to check. The st_mode of 100644 should *not* boil down to `-r--r--r--`.

**Comment by Marabon** [comment] 2019-08-09 17:31
Yeah, just tried it after removing that workaround
```
struct stat {
    st_dev = 0
   st_mode = 100600 (octal)
  st_nlink = 1
    st_ino = 0
    st_uid = 197609
    st_gid = 197609
   st_rdev = 0
   st_size = 864775589
 st_blocks = 1689016
st_blksize = 0
}
```
As you guessed it's 100600, and the permissions are the same as they used to when we started this
```
$ ls -l
total 844516
---------- 1 x x 864775589 Jun 23  2018 12.monkeys.s04e06.720p.web.x264-tbs.mkv
-rwxrwxr-x 1 x x        47 Jul 25  2018 12.monkeys.s04e06.720p.web.x264-tbs.nfo
-rwxrwxr-x 1 x x       900 Jul 25  2018 12.monkeys.s04e06.720p.web.x264-tbs.sfv
```

**Comment by hasse69** [comment] 2019-08-09 17:56
Yes, that information you now posted would be good to send in an issue report to WinFSP/FUSE.
Maybe @billziss-gh can come up with some ideas how to debug this further?

**Comment by hasse69** [comment] 2019-08-09 19:39
Another thing that struck me just now is that we have been chasing a problem believed to be associated with a certain file or files. I see that as very unlikely to be honest. If you run the same log and stat a file that you *believe* is working (readable) my guess is still that the st_mode reported from rar2fs is not propagated properly by the next layer(s). It just happens to be that the read-access bit becomes set.

**Comment by hasse69** [comment] 2019-08-16 21:09
@Marabon 
Any news here? Did you try to dump the stat output from another ("working") file to see if the st_mode field might actually not match what is reported from `ls -l`?
Anyways, I have added a new option `--no-inherit-perm` that will ignore whatever is set in the archive and use the default instead. This patch is not yet pushed though but hopefully sooner than later.
Also, unless you have something additional to add, I wish to close this issue.

**Comment by Marabon** [comment] 2019-08-16 22:35
Sorry, I didn't dump the stat output from another file.

I don't think I have anything additional to add so you can close the issue as this most likely isn't an error with rar2fs. The new option will be a good workaround though, so that's a nice addition.

**Comment by hasse69** [comment] 2019-08-17 07:42
The only concern I have here is that even with the new option, something is not coming out right on your system. As we tried previously, a mode of `100644` still gave you only read permission, which is fine for your specific use-case, but still is not correct. Setting mode to `100644` is basically what the new option will do.

**Comment by Marabon** [comment] 2019-08-17 08:34
Yes, you are correct, it's pretty much just luck that it works for what my purpose is, if I had other tasks planned with the file it could've just as well not have worked at all. 

In the new issue I've posted my windows and winfsp builds.
I'm clueless as to why this is acting up on my system, and I suppose even with the exact same windows build etc it might not be too easy to reproduce. 
I guess we'll just have to wait and hope that this information is enough for @billziss-gh to at least get some idea of where the issue may be. 

Your help, or attempt to help at least, is very much appreciated, and at least we came up with a workaround for my specific issue. :)

**Comment by hasse69** [comment] 2019-08-18 21:25
I have pushed https://github.com/hasse69/rar2fs/commit/3692a462028830e45d117d900069a27203b5ecd9 now.
Please try it and report back if it works or not.

**Comment by Marabon** [comment] 2019-08-18 21:38
--no-inherit-perm gives
```
$ ls -l
total 844516
-r--r--r-- 1 x x 864775589 Jun 23  2018 12.monkeys.s04e06.720p.web.x264-tbs.mkv
-rwxrwxr-x 1 x x        47 Jul 25  2018 12.monkeys.s04e06.720p.web.x264-tbs.nfo
-rwxrwxr-x 1 x x       900 Jul 25  2018 12.monkeys.s04e06.720p.web.x264-tbs.sfv

```

**Comment by hasse69** [comment] 2019-08-18 21:48
Sorry, push went sideways, this is the one to use https://github.com/hasse69/rar2fs/commit/907ab3141476b1d1f0fbc05f2b2a27928508d6db

**Comment by billziss-gh** [comment] 2019-08-19 14:21
Sorry for the late response, but I have been on a rather long vacation. I am trying to catch up to email and GitHub issues, but should be able to have some comments on this or the related WinFsp issue soon.

**Comment by hasse69** [comment] 2019-08-19 15:06
@billziss-gh 
No problem, I am simply looking forward to get help understanding the underlying reason for this weird behavior. Since there is a workaround available it is not critical in anyway, just annoying :)

**Comment by hasse69** [comment] 2019-08-22 18:13
I think we got what we need from https://github.com/billziss-gh/winfsp/issues/245.
Closing.

**Closed by hasse69** 2019-08-22 18:13 UTC
Labels: Other
