### ISSUE TITLE
Systemd example has an error.

### ISSUE THREAD

**Issue by SentinelCQ** [hasse69/rar2fs#156] opened 2021-02-15 03:09 UTC
In the Wiki, there is an example for enabling systemd automount. The Unit file for the .mount has the following.

[Mount]
What=/mnt/mymount/rarfiles
Where=/mnt/mymount/magic
Type=fuse.rar2fs
Options=allow_other

[Install]
WantedBy=multi-user.target

But the current install only installs /usr/local/sbin/mount.rar2fs 
As such the mount fails, and unfortunately only gives the unhelpful error code 32 which is just mount failed. 

After modifying the Type= line to say
Type=rar2fs
instead of 
Type=fuse.rar2fs
it works.

**Comment by hasse69** [comment] 2021-02-15 06:29
Thanks for the observation.
Since I am not actually the author of that section in the Wiki I have instead invited you to the project collaborators.
Once accepted, feel free to update the Wiki and close the issue when done.

**Comment by SentinelCQ** [comment] 2021-02-15 13:46
I have updated the wiki with what worked for me using the current rar2fs as of Feb. 2021.

Will wait for a day or two to see if @zimme has a comment and otherwise will close the issue.

Thanks for the quick response.

**Comment by zimme** [comment] 2021-02-15 13:47
Can't remember contributing something about systemd, I added some info relates to threads and musl. Just a quick search about mounting fuse filesystems using systemd the type should be fuse.sshfs, fuse.rar2fs etc. However something might have changed in systemd?

**Comment by hasse69** [comment] 2021-02-15 13:52
> Can't remember contributing something about systemd, I added some info related to threads and musl.

Sorry, my memory failed me. You are of course absolutely right, sorry for the spam :(

**Comment by SentinelCQ** [comment] 2021-02-15 16:03
Sure. I also got tripped up when I tried to add it via the fstab

rar2fs#/mnt/mymount/rarfiles /mnt/mymount/magic fuse rw,allow_other 0 0 

I didn't end up trying it with just rarfs as the fstype in the list instead of fuse.

**Comment by zimme** [comment] 2021-02-15 16:13
>The programs mount and umount support filesystem subtypes. The subtype is defined by a '.subtype' suffix. For example 'fuse.sshfs'. It's recommended to use subtype notation rather than add any prefix to the mount source (for example 'sshfs#example.com' is deprecated).

**Comment by hasse69** [comment] 2021-02-20 08:55
Can we close this issue now?

**Comment by zimme** [comment] 2021-02-22 08:02
The wiki has been updated and we know the cause of the problem so people running into this problem should be able to find a solution either here in the issues or on the wiki.

I'd say it's fine to close.

**Closed** 2021-02-22 08:03 UTC
