### ISSUE TITLE
Invalid timestamp inheritance

### ISSUE THREAD

**Issue by jyhpsycho** [hasse69/rar2fs#80] opened 2017-07-22 04:22 UTC
* HOW TO REPRODUCE
  - NOTE : I'll explain the procedure with outputs for each command, which helps understand what's the problem.
```
$ touch X
$ ls -lA --full-time
total 0
-rw-r--r-- 1 rar_work users 0 2017-07-22 13:10:30.792039960 +0900 X
$ mkdir Y
$ touch X
$ ls -lA --full-time
total 4
-rw-r--r-- 1 rar_work users 65 2017-07-22 13:10:48.397625119 +0900 TEST.rar
-rw-r--r-- 1 rar_work users  0 2017-07-22 13:11:06.914188814 +0900 X
drwxr-xr-x 2 rar_work users 40 2017-07-22 13:11:03.593267065 +0900 Y
$ rar2fs -o ro,allow_other --show-comp-img TEST.rar Y
$ ls -lA --full-time Y
```

* EXPECTED OUTPUT
```
total 0
-rw-r--r-- 1 rar_work users 0 2017-07-22 13:10:30.792039960 +0900 X
```
* ACTUAL RESULT
```
total 0
-rw-r--r-- 1 rar_work users 0 2017-07-22 13:11:06.914188814 +0900 X
```

* SYSTEM INFORMATION
```
$ rar2fs --version
rar2fs v1.25.2 (DLL version 8)    Copyright (C) 2009 Hans Beckerus
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under
certain conditions; see <http://www.gnu.org/licenses/> for details.
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

$ emerge --search '%^unrar$'

[ Results for search key : %^unrar$ ]
Searching...

*  app-arch/unrar
      Latest version available: 5.5.5-r1
      Latest version installed: 5.5.5-r1
      Size of files: 216 KiB
      Homepage:      http://www.rarlab.com/rar_add.htm
      Description:   Uncompress rar files
      License:       unRAR

[ Applications found : 1 ]
```

 * ADDITIONAL NOTES
   - It incorrectly references metadata(not only timestamp!) from same name entry located on mounted RAR file at mount time. It even changes to directory(!) if you do `( rm X; mkdir X )` instead of second `touch X`.

**Comment by hasse69** [comment] 2017-07-22 13:47
Thanks. But I do not really follow the steps to reproduce this. There seems to be some commands missing from the list? Like how you created the `TEST.rar` file etc. 
The `rm X;` command you mention is that made on the folder above the `Y` mount point? Then how is it possible for rar2fs to catch any information from that?

**Comment by jyhpsycho** [comment] 2017-07-22 15:40
Ah, I missed archive create command. It's only missed thing, I think.
```
rar a -ma5 TEST.rar X
```
It may run before creating directory Y.

Command `touch X` I mentioned is second one, after `mkdir Y`. Its order is not important, but should run before mounting archive.

**Comment by jyhpsycho** [comment] 2017-07-22 15:54
Hmm, I'll show it once more.
* NOTE : I used rar under WINE, not unix version. But I think it does not affect to this issue.
```
$ touch X
$ ls -lA --full-time
total 0
-rw-r--r-- 1 rar_work users 0 2017-07-23 00:43:54.106698936 +0900 X
$ rar a -ma5 TEST.rar X
fixme:heap:RtlSetHeapInformation 0x240000 0 0x23fd30 4 stub
fixme:file:SetDefaultDllDirectories (800): stub

RAR 5.31   Copyright (c) 1993-2016 Alexander Roshal   4 Feb 2016
Trial version

Creating archive TEST.rar

Adding    X                                                           OK 
Done
$ rm X
$ mkdir X
$ mkdir Y
$ ls -lA --full-time
total 4
-rw-r--r-- 1 rar_work users 65 2017-07-23 00:45:46.006061204 +0900 TEST.rar
drwxr-xr-x 2 rar_work users 40 2017-07-23 00:47:37.917423189 +0900 X
drwxr-xr-x 2 rar_work users 40 2017-07-23 00:48:03.249826252 +0900 Y
$ rar2fs -o ro,allow_other --show-comp-img TEST.rar Y
$ ls -lA --full-time Y
total 0
drwxr-xr-x 2 rar_work users 40 2017-07-23 00:47:37.917423189 +0900 X
```

The archive I created has only zero-size file, NOT directory...

**Comment by hasse69** [comment] 2017-07-23 07:03
> NOTE : I used rar under WINE, not unix version. But I think it does not affect to this issue.

Correct. This has nothing to do with WINE.
It seems the root path lookup for archive mounts goes wrong, folder mounts work as expected.

**Comment by hasse69** [comment] 2017-09-22 22:44
Sorry for the delayed response! Been really occupied with unrelated matters and had to prioritize.
Please try this patch on master/HEAD to see if it resolves the issue.
[patch.80.1.txt](https://github.com/hasse69/rar2fs/files/1326024/patch.80.1.txt)

**Comment by hasse69** [comment] 2017-10-11 18:12
Since I am not getting any feedback on this I will soon close this issue assuming the issue is resolved. If that is not the case please file a new issue.

**Closed** 2017-10-12 18:18 UTC
Labels: Defect, Priority-Medium
