### ISSUE TITLE
File compare failed on multi-volume archive which is not compressed.

### ISSUE THREAD

**Issue by jyhpsycho** [hasse69/rar2fs#42] opened 2015-12-16 18:19 UTC
I usually checks integrity of data on created rar archive via rar2fs; Because I'm using Windows version of WinRAR under Linux, and there's many suspicious things that decreases its reliability, i.e. WINE bug, silent data corruption on disk, etc. Sometimes I find out data differences in practice when I processing several terabytes of data. The nice features of RAR format(Checksum, Recovery Record) helps me to detect these errors, and even recover it.

When I compare contents on certain archive using diff, it throws error message that these files are differ. With some experiments, I found some conditions that occuring this issue:

 * RARv5 format (older format is not tested).
 * Volume-splitted.
 * File path contains some special characters.
 * Has recovery record.

I created the sample archive reproduces it by following instructions:
```bash
mkdir W
mkdir 'CJK文字집합ディレクトリー/[$637!@1 ^#special character set#^]'
dd if=/dev/urandom of='CJK文字집합ディレクトリー/[$637!@1 ^#special character set#^]/random' bs=1k count=64
rar a -m0 -ma5 -rr10 -v30720b TEST.rar 'CJK文字집합ディレクトリー'
rar2fs -o ro,allow_other --flat-only --show-comp-img TEST.part1.rar W
diff 'CJK文字집합ディレクトリー' 'W/CJK文字집합ディレクトリー'
```
Note that the file path contains non-alphabetical characters(some symbols, CJK). I'll attach the sample, too.

Additional informations :

1) Software versions
   * Using libunrar 5.3.8.
```
# ./rar2fs-master/rar2fs --version

rar2fs v1.21.1 (DLL version 7)    Copyright (C) 2009-2014 Hans Beckerus
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under
certain conditions; see <http://www.gnu.org/licenses/> for details.
FUSE library version: 2.9.4
fusermount version: 2.9.4
using FUSE kernel interface version 7.19
```
2) Output of 'unrar vta'
```
UNRAR 5.30 freeware      Copyright (c) 1993-2015 Alexander Roshal

Archive: TEST.part1.rar
Details: RAR 5, volume 1, recovery record

        Name: CJK文字집합ディレクトリー/[$637!@1 ^#special character set#^]/random
        Type: File
        Size: 65536
 Packed size: 28369
       Ratio: -->
       mtime: 2015-12-17 02:22:26,177
  Attributes: ..A....
  Pack-CRC32: DF1FB266
     Host OS: Windows
 Compression: RAR 5.0(v50) -m0 -md=128K

        Name: QO
        Type: Service
        Size: 124
 Packed size: 124
       Ratio: 100%
  Attributes: .B
     Host OS: Windows
 Compression: RAR 5.0(v50) -m0 -md=128K

        Name: RR
        Type: Service
        Size: 1312
 Packed size: 1312
       Ratio: 100%
  Attributes: .B
     Host OS: Windows
 Compression: RAR 5.0(v50) -m0 -md=128K

     Service: EOF
```
3) Output of 'cmp -l' (original data first, rar2fs' output second)
```
28370 312 147
28371 147 267
28372 267 137
28373 137 274
28374 274 246
28375 246 346
28376 346 376
28377 376 302
28378 302  25
28379  25 371
.
.
.
56734   5 361
56735 361 170
56736 170  12
56737  12  47
56738 312 130
56739  47 240
56740 130 323
56741 240 210
56742 323 165
56743 210  37
.
.
.
```
According to 2) and 3), It seems that rar2fs misses 1 byte of data per volume.

[TEST.zip](https://github.com/hasse69/rar2fs/files/64360/TEST.zip)

**Comment by jyhpsycho** [comment] 2015-12-16 18:31
NOTE : In the reproduce instructions, I'm using rar2fs 1.21.0 that supported by Gentoo portage. I checked the recent master source(1.21.1, in 'Software versions') and it occurs, too.

**Comment by hasse69** [comment] 2015-12-16 18:59
Is this possible to reproduce without a recovery record? I really doubt that it has anything to do with special characters, and libunrar is used for extraction of compressed data. Also, what happens if you try the same operation but use store mode -m0?  
A test of the same data using rar4 would also be appreciated.

Thanks.
Hans

**Comment by jyhpsycho** [comment] 2015-12-16 19:26
1. Yes, it's reproducible without RR.
2. I used -m0 with original report. Using -m5 -ma5 does not reproduce this issue.
3. With -m0 -ma0 (using legacy format) does not reproduce this issue.

**Comment by jyhpsycho** [comment] 2015-12-16 19:35
Additional information : Special characters in file path does not affect to this issue. I tested with just using 'T1' for pathname and it occurs.

I seen another issue may related with special character file path(compressed small file throws I/O error, on huge archive), but it cannot reproducible with smaller testcases I tried before. I'll also report that issue when I can reproduce it with smaller testcase.

**Comment by hasse69** [comment] 2015-12-16 20:01
What is -ma<X> ? Cannot recall ever seeing that one before, at least not for RAR4?
Anyway, this then looks like a RAR5 unique problem in combination with volumes. Strange really. 
I thought I got this one right, obviously not :( I will look into this when time allows.

**Comment by jyhpsycho** [comment] 2015-12-16 20:08
From Rar.txt in installed WinRAR:

```
    -ma[4|5]
            Specify a version of archiving format.

            By default RAR creates archives in RAR 4.x format.
            Use -ma5 or just -ma to create RAR 5.0 archives.
            Use -ma4 in case you need to override -ma5 saved
            in configuration and force RAR to use RAR 4.x format.

            This switch is used only when creating a new archive.
            It is ignored when updating an existing archive.
```

I used -ma0 instead of -ma4, it creates legacy archive format, too.

**Comment by hasse69** [comment] 2015-12-16 20:54
Ok, thanks. 
FYI I can say that it was rather easy to reproduce. It was also extremely easy to fix. But I cannot fully understand why that is the case! So a patch for this needs to wait until I can explain what is going on. I tested RAR5 volumes very carefully when introduced and code needed back then now seem to make everything break instead!

**Comment by hasse69** [comment] 2015-12-16 21:54
The problem seems to be that old libunrar versions did not properly set RAR unpack version. This in turn resulted in a "off by one" bug due to wrong header size being reported. This was compensated for in rar2fs but with later (currently unknown) versions of libunrar the size is reported correctly. That makes the compensation go sideways. I have sent a question to the libunrar maintainer at rarlabs, so until I know exactly in which version this was fixed a patched cannot be released. We still need to apply the compensation for backwards compatibility.

**Comment by jyhpsycho** [comment] 2015-12-16 22:25
Well, there's too many libunrar version... In the worst case, we can find out it by testing all libunrar version available on ftp://ftp.rarlab.com/rar/. Exhaustive compiling may not be needed if the maintainer of libunrar tells that, though...

**Comment by hasse69** [comment] 2015-12-16 23:05
Yes, trial and error is always an option. But as you say, there are a lot of version to try. I would prefer to get the information from official sources.

**Comment by hasse69** [comment] 2015-12-18 00:48
There is now a fix for this issue pushed to master.

**Comment by jyhpsycho** [comment] 2015-12-18 14:18
Test failed... :-( It's work with provided sample, though.

3988852017 101 264
3988852018 215  60
3988852019 156 171
3988852020 114 151
3988852021   4 265
3988852022 165  52
3988852023 336  50
3988852024 120 343
3988852025 152 215
3988852026   0 177
3988852027   5 325
3988852028 211   4
3988852029 276  61
3988852030 152 346
3988852031 204 371
3988852032 267 354
3988852033 212  44
3988852034 115 261
3988852035   1 161
3988852036 353  34
3988852037 105 107
3988852038 254  20
3988852039 332  21
3988852040  27  30
3988852041 301 173
3988852042 304  36
3988852043 105 135
3988852044  44  16
3988852045 165 260
3988852046 162  53
3988852047 131  10
3988852048  30  43
3988852049 224  22
3988852050 322  12
3988852051  41 226
3988852052 110 341
3988852053 206 313
3988852054 363 252
3988852055 166 131
3988852056   5 144
3988852057 122  32
3988852058  44  56
3988852059 261 205
3988852060 201 315
3988852061 242 247
3988852062 107 225
3988852063  20 160
3988852064  21 107
3988852065  34 200
3988852066  25  50
3988852067 245  12
3988852068 304 311
3988852069  25 261
3988852070 344  37
3988852071 120 311
3988852072 331 217
3988852073 103 210
3988852074  42 330
3988852075  22 324
.
.
.

What's happened?! It doesn't seems to have any regularity like one-byte-shift...

**Comment by jyhpsycho** [comment] 2015-12-18 15:06
Currently I'm tryng to reproduce it with random data. But, there's no case reproduce it found. I'll try it more.

**Comment by jyhpsycho** [comment] 2015-12-18 16:38
Finally I reproduced it. Following instruction is used for producing sample.

```
mkdir TEST_DIR O
mkdir TEST_DIR/DIR{1..3}
mkdir TEST_DIR/DIR1/{A,B}
mkdir TEST_DIR/DIR2/C
dd if=/dev/urandom of=DIR1/A/FILE1 bs=4k count=16
dd if=/dev/urandom of=DIR1/A/FILE2 bs=4k count=16
dd if=/dev/urandom of=DIR1/B/FILE3 bs=4k count=16
dd if=/dev/urandom of=DIR2/C/FILE4 bs=4k count=16
dd if=/dev/urandom of=DIR2/FILE5 bs=4k count=16
rar a -m0 -ma5 -v16000b -rr5 -qo+ TEST.rar TEST_DIR
./rar2fs-master/rar2fs -o ro,allow_other --flat-only --show-comp-img TEST.part01.rar O
diff -ur TEST_DIR O/TEST_DIR
```

Note that it uses -qo+ option. It stores 'Quick open information' for all files in RAR archive.

NOTE : Directory hierarchy building provided sample is created on tmpfs; It returns the file list as reverse order of being created. It's not important thing for this issue, but one may confuse that it does not store files as typical order.

[TEST.zip](https://github.com/hasse69/rar2fs/files/66866/TEST.zip)

**Comment by jyhpsycho** [comment] 2015-12-18 16:47
It seems to be just another issue. With -qo- option(it does not create any 'Quick open information'), it doesn't occur... Should I create another issue report?

**Comment by hasse69** [comment] 2015-12-18 17:07
Is the only problem you see now that binary compare does not work if you use the quick open feature?
Or did I severely misunderstand something?

**Comment by jyhpsycho** [comment] 2015-12-18 17:14
Yes, It seems only occurs with Quick open information feature. Without that, the compare result is equal.

**Comment by jyhpsycho** [comment] 2015-12-18 17:40
OK, I'll open the new issue. It seems that this issue can be closed; as "Mis-read stored data from RARv5 volume-splitted archive due to incorrect header data, up to libunrar 5.3.6". If not, it can be repoened or writing new issue.

**Comment by hasse69** [comment] 2015-12-18 20:53
We cannot close this yet. It is too easy to reproduce by simply creating archives with multiple files in volumes. It works fine for legacy format but for RAR5 it is unfortunately broken. I have no simple answer to what has gone wrong. This will require some time to debug, time that I am currently lacking :(
The quick escape  route (which would also solve the quick open issue) is to basically fall-back to native read of RAR5 archives and use the libunrar extraction routines also for store mode. That obviously has other drawbacks but will at least make RAR5 archives extract properly.

**Comment by hasse69** [comment] 2015-12-23 00:18
I have more or less concluded what is the problem. Now I need to figure out how to fix it. 
There are limitations in the libunrar API that does not really allow a user to do whats needed in this case.

**Comment by hasse69** [comment] 2015-12-23 10:21
It seems I have a working solution now. But I need to perform more tests and some additional cleanup.
I have no ETA currently to when this will be ready.

**Comment by jyhpsycho** [comment] 2015-12-23 12:52
OK, Please provide the patch(or just commit?) when ready. I'll test it.

**Comment by hasse69** [comment] 2015-12-23 23:20
Here is a patch to try out. It is not yet completely finished for pushing to master but it should only be a matter of minor editorial changes.

[issue_42.patch.zip](https://github.com/hasse69/rar2fs/files/71312/issue_42.patch.zip)

**Comment by jyhpsycho** [comment] 2015-12-29 15:48
OK, It seems to be work with RARv5 format, but I found the similar issue with legacy foramt, too. I'll try to reproduce it with smaller case.

**Comment by hasse69** [comment] 2015-12-29 18:22
Please do. I tried the patch on several different archives in both RAR5 and legacy format without any issues. But it is very possible that there are slip throughs. The patch should make legacy format more robust too since it no longer assume a certain header size.

**Comment by jyhpsycho** [comment] 2015-12-29 21:47
Reproduced by very similar commands in [comment](https://github.com/hasse69/rar2fs/issues/42#issuecomment-165829091), changing just one line for archive creation. Check the sample.
```
rar a -m0 -ma0 -v55000b TEST.rar TEST_DIR
```

It divides contained file across two archives(e.g. FILE5 is on part1 and part2, FILE2 is on part4 and part5, etc.), and diff reports that all of archive contents is differ than the data used for create it.

[TEST.zip](https://github.com/hasse69/rar2fs/files/74380/TEST.zip)

**Comment by jyhpsycho** [comment] 2015-12-29 21:53
It seems to regression of that patch... It doesn't occur with 1.21.0 installed on my system.

**Comment by hasse69** [comment] 2015-12-29 23:27
Right. Back to the drawing board.

**Comment by hasse69** [comment] 2015-12-30 00:08
Try this one.

[issue_42_v2.patch.zip](https://github.com/hasse69/rar2fs/files/74492/issue_42_v2.patch.zip)

**Comment by hasse69** [comment] 2016-01-06 15:19
Any news on testing the last patch?

**Comment by jyhpsycho** [comment] 2016-01-08 03:54
Oh, sorry for late reply. I have very little spare time to test it last week, and it's completed at right now with all of my testcases. It seems to work. Thanks :-)

**Comment by hasse69** [comment] 2016-01-08 09:50
Patch applied and pushed to master.

**Closed by hasse69** 2016-01-08 09:50 UTC
Labels: Priority-Medium, Type-Defect
