### ISSUE TITLE
Invalid behavior of volume name scan

### ISSUE THREAD

**Issue by jyhpsycho** [hasse69/rar2fs#65] opened 2017-01-21 09:20 UTC
* HOW TO REPRODUCE
1) Create sample.
```
$ mkdir DIR_1
$ mkdir DIR_2
$ dd if=/dev/urandom of=DIR_1/FILE_1_1 bs=1k count=64
$ dd if=/dev/urandom of=DIR_1/FILE_1_2 bs=1k count=64
$ dd if=/dev/urandom of=DIR_2/FILE_2_1 bs=1k count=64
$ dd if=/dev/urandom of=DIR_2/FILE_2_2 bs=1k count=64
```
2) Create archive.
```
$ rar a -m0 -ma5 -ep1 TEST.vol1.rar DIR_1
$ rar a -m0 -ma5 -ep1 TEST.vol2.rar DIR_2
```
3) Place archive on same directory.
```
$ mkdir RARs
$ mv *.rar RARs
```
4) Mount one archive file.
```
$ mkdir M
$ rar2fs --flat-only --show-comp-img -o ro,allow_other RARs/TEST.vol1.rar M
```
5) Listing.
```
$ ls -lAR M
```

 * EXPECTED RESULT
```
M:
total 8
drwxr-xr-x 2 rar_work users 4096 Jan 21 18:05 DIR_1

M/DIR_1:
total 136
-rw-r--r-- 1 rar_work users 65536 Jan 21 18:05 FILE_1_1
-rw-r--r-- 1 rar_work users 65536 Jan 21 18:05 FILE_1_2
```

 * ACTUAL RESULT
```
M:
total 16
drwxr-xr-x 2 rar_work users 4096 Jan 21 18:05 DIR_1
drwxr-xr-x 2 rar_work users 4096 Jan 21 18:05 DIR_2

M/DIR_1:
total 136
-rw-r--r-- 1 rar_work users 65536 Jan 21 18:05 FILE_1_1
-rw-r--r-- 1 rar_work users 65536 Jan 21 18:05 FILE_1_2

M/DIR_2:
total 136
-rw-r--r-- 1 rar_work users 65536 Jan 21 18:05 FILE_2_1
-rw-r--r-- 1 rar_work users 65536 Jan 21 18:05 FILE_2_2
```

As you see, It treats TEST.vol2.rar is part of archive 'TEST', but it's not actually. Multi-volume archive has fixed name scheme(r00, r01, ... for old one and .part1.rar, .part2.rar, ... for new one), and has some flag on internal structure. For directory mount, it's expected behavior because all archive on directory should be mounted.

**Comment by jyhpsycho** [comment] 2017-01-21 09:24
Write as regular expression, new scheme should be matched with "(.*)\.part[0-9]+\.rar", which the part in parenthesis is identical. For old scheme, it will be "(.*).r[0-9]{2}".

**Comment by hasse69** [comment] 2017-01-21 12:43
The new format is not that strict. rar2fs use a support function from libunrar to calculate next file name.
There is a problem with that obviously. That function assumes it is called for a confirmed volume, since it is not a representation of the file format itself. This issue was introduced as a result of the slow mounting for encrypted archives. Previously rar2fs basically used full analysis of the entire volume. I need to add at least extraction of the header in the first file to know if it is a volume or not. Trying to write a function that can mimic all permutations of the new volume format is not future proof, hence the reason to use the support function in libunrar instead.

**Comment by hasse69** [comment] 2017-01-21 13:04
Actually, there are no strict rules at all except for old style archives that must follow the .rNN semantics.
You can easily try for yourself by renaming a volume using the new style format, eg. .000, .001 etc. and completely remove the .partN. from the names. The unrar tool will still be able to extract it.  UnRAR/WinRAR looks for any possible sequential pattern in the filename. If it finds that and it is not old style format it will figure out next name automatically.

**Comment by jyhpsycho** [comment] 2017-01-21 16:46
Ah... I don't know that before, becuase WinRAR generates the volume file name as explained above on most cases :-( But I think it's problematic.

**Comment by hasse69** [comment] 2017-01-21 17:29
I solve it somehow :)

**Comment by hasse69** [comment] 2017-01-22 01:01
Please test and report.

**Comment by hasse69** [comment] 2017-01-24 22:53
Closing this since sample provided now works as expected.

**Closed by hasse69** 2017-01-24 22:53 UTC
Labels: Defect, Priority-Medium

**Comment by jyhpsycho** [comment] 2017-01-26 14:14
OK, It works with archive I found this issue. Thanks.
