### ISSUE TITLE
Throws I/O error when accessing compressed file under very long pathname.

### ISSUE THREAD

**Issue by jyhpsycho** [hasse69/rar2fs#43] opened 2015-12-16 21:08 UTC
#### * CAUTION : unrar can extract the sample file correctly, but extracted file is cannot be accessed or deleted on "Real Windows" environment due to that's long pathnames. For deleting that files, using 7-zip file manager. On linux, there's no problem.

Finally I can reproduce this issue, then report it.

I guessed some special characters(CJK characters or non-alphanumerical symbols) causes this issue before, but it's not true. It occurs with compressed file which has very long pathname(over 256(?) bytes total). It just easily find out when using CJK characters which consumes 3 byte(in UTF-8, most of character encodings on linux terminal, file name of filesystem, etc.) per each character.

 * How to reproduce
```bash
mkdir W
mkdir -p 'base_dir_for_very_long_file_paths/it_has_very_long_directory_name_for_testing_rar2fs_functionality/this_is_third_level_of_directory_hierarchy_only_using_alphanumeric_latin_characters/this_is_fourth_level_of_directory_hierarchy_only_using_alphanumeric_latin_characters'
dd if=/dev/zero of='base_dir_for_very_long_file_paths/it_has_very_long_directory_name_for_testing_rar2fs_functionality/this_is_third_level_of_directory_hierarchy_only_using_alphanumeric_latin_characters/this_is_fourth_level_of_directory_hierarchy_only_using_alphanumeric_latin_characters/this_is_file_for_testing' bs=1M count=16
rar a -m5 -ma5 TEST.rar base_dir_for_very_long_file_paths
rar2fs -o ro,allow_other --flat-only --show-comp-img TEST.rar W
diff -ur W/base_dir_for_very_long_file_paths base_dir_for_very_long_file_paths
```

 * Additional information
   * I'll attach the sample, but read the CAUTION above before deal with it!
   * It doesn't occur with stored file. Only compressed file causes I/O error.
   * It occurs with both of legacy and newer RAR format.
   * Using libunrar 5.3.8.
```
# ./rar2fs-master/rar2fs --version
rar2fs v1.21.1 (DLL version 7)    Copyright (C) 2009-2014 Hans Beckerus
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under
certain conditions; see <http://www.gnu.org/licenses/> for details.
FUSE library version: 2.9.4
fusermount version: 2.9.4
using FUSE kernel interface version 7.19
```
[TEST.zip](https://github.com/hasse69/rar2fs/files/64553/TEST.zip)

**Comment by jyhpsycho** [comment] 2015-12-16 21:22
NOTE : I don't use the linux console version of RAR. 'rar' in commandline is just alias that invoking WINE for using Windows version of RAR executable.

**Comment by hasse69** [comment] 2015-12-16 21:49
Thanks for the report. I will try this too. 
But as it seems to happen only for compressed archives it sounds more like a problem with libunrar rather than rar2fs or could it even be something with WINE (again?).

**Comment by jyhpsycho** [comment] 2015-12-16 22:01
Hmm... The sample is produced by WinRAR under WINE, but I tried to extract it under Windows and it succeed. But it cannot be accessed or even deleted using Windows explorer, thus I warned that. I guess it's not the libunrar's issue because I used Windows version of unrar on Windows environment for extraction testing, not using WinRAR itself or using WINE...

**Comment by jyhpsycho** [comment] 2015-12-16 22:04
Additional information : Linux version of unrar compiled from source can extract the sample, too.

**Comment by hasse69** [comment] 2015-12-16 23:02
Yes, but libunrar and WinRAR and even unrar tool (though using same source code tree) is not using exactly the same implementation. There are compile time settings used to pick proper code.
I am currently digging deep in the libunrar source tree since all rar2fs is doing is calling the API to extract the file. I see no reason why it should not work.

**Comment by jyhpsycho** [comment] 2015-12-19 03:34
I just compiled rar2fs with --enable-debug=3, and it shows various debug message like return value of function. It does not show any message causes by [line #1234](https://github.com/hasse69/rar2fs/blob/master/rar2fs.c#L1234) - "lread_rar: RETURN xx". By tracking control flow, I found that lread_rar() early returns at [line #1153](https://github.com/hasse69/rar2fs/blob/master/rar2fs.c#L1153).

I cannot understand what it checks... :-(

**Comment by jyhpsycho** [comment] 2015-12-19 03:45
Modify line 1152-1153 to:
```C
if (!op->buf->offset) {
        printd(3, "%s: after sync_thread_read() failed.\n", __func__);
        return op->entry_p->flags.encrypted ? -EPERM : -EIO;
}
```

Output messages:
```
unique: 75, opcode: OPEN (14), nodeid: 6, insize: 48, pid: 13159
open flags: 0x8000 /base_dir_for_very_long_file_paths/it_has_very_long_directory_name_for_testing_rar2fs_functionality/this_is_third_level_of_directory_hierarchy_only_using_alphanumeric_latin_characters/this_is_fourth_level_of_directory_hierarchy_only_using_alphanumeric_latin_characters/this_is_file_for_testing
rar2_open()   /base_dir_for_very_long_file_paths/it_has_very_long_directory_name_for_testing_rar2fs_functionality/this_is_third_level_of_directory_hierarchy_only_using_alphanumeric_latin_characters/this_is_fourth_level_of_directory_hierarchy_only_using_alphanumeric_latin_characters/this_is_file_for_testing
(13155) OPEN    /base_dir_for_very_long_file_paths/it_has_very_long_directory_name_for_testing_rar2fs_functionality/this_is_third_level_of_directory_hierarchy_only_using_alphanumeric_latin_characters/this_is_fourth_level_of_directory_hierarchy_only_using_alphanumeric_latin_characters/this_is_file_for_testing [0x0][called from 13159]
(13155) ALLOC   /base_dir_for_very_long_file_paths/it_has_very_long_directory_name_for_testing_rar2fs_functionality/this_is_third_level_of_directory_hierarchy_only_using_alphanumeric_latin_characters/this_is_fourth_level_of_directory_hierarchy_only_using_alphanumeric_latin_characters/this_is_file_for_testing [0x7f04880219a0  ]
preload_index()   /base_dir_for_very_long_file_paths/it_has_very_long_directory_name_for_testing_rar2fs_functionality/this_is_third_level_of_directory_hierarchy_only_using_alphanumeric_latin_characters/this_is_fourth_level_of_directory_hierarchy_only_using_alphanumeric_latin_characters/this_is_file_for_testing
   open[139657438435632] flags: 0x8000 /base_dir_for_very_long_file_paths/it_has_very_long_directory_name_for_testing_rar2fs_functionality/this_is_third_level_of_directory_hierarchy_only_using_alphanumeric_latin_characters/this_is_fourth_level_of_directory_hierarchy_only_using_alphanumeric_latin_characters/this_is_file_for_testing
   unique: 75, success, outsize: 32
unique: 76, opcode: READ (15), nodeid: 6, insize: 80, pid: 13159
read[139657438435632] 4096 bytes from 0 flags: 0x8000
rar2_read()   size=4096, offset=0, fh=139657438435632
PID 13155 calling lread_rar(), seq = 1, size=4096, offset=0/0
lread_rar: after sync_thread_read() failed.
   unique: 76, error: -5 (Input/output error), outsize: 16
unique: 77, opcode: READ (15), nodeid: 6, insize: 80, pid: 13159
read[139657438435632] 4096 bytes from 0 flags: 0x8000
rar2_read()   size=4096, offset=0, fh=139657438435632
PID 13155 calling lread_rar(), seq = 2, size=4096, offset=0/0
lread_rar: after sync_thread_read() failed.
   unique: 77, error: -5 (Input/output error), outsize: 16
unique: 78, opcode: FLUSH (25), nodeid: 6, insize: 64, pid: 13159
flush[139657438435632]
rar2_flush()   
(13155) FLUSH [0x7f04880219a0  ][called from 13159]
lflush()   
   unique: 78, success, outsize: 16
unique: 79, opcode: RELEASE (18), nodeid: 6, insize: 64, pid: 0
release[139657438435632] flags: 0x8000
rar2_release()   
(13155) RELEASE [0x7f0488021930    ]
(13155) FREE [0x7f0488021930    ]
   unique: 79, success, outsize: 16
```

The sample provided above sometimes does not reproduce it. Thus I created another sample that contains just 384-byte-long file contains null data, not 16MiB.

[TEST.zip](https://github.com/hasse69/rar2fs/files/67358/TEST.zip)

**Comment by hasse69** [comment] 2015-12-19 10:30
The problem is most likely in extract_rar().
I actually found an issue but it showed that it was not it. The call to RARProcessFile() in libunrar seems to fail. Might be a libunrar issue, it has limitation to 260 chars in some legacy functions. Might be it is triggered some how.

**Comment by jyhpsycho** [comment] 2015-12-19 12:27
Well... libunrar has following function:

```C
// libunrar 5.3.8, dll.cpp, Line 160.
int PASCAL RARReadHeader(HANDLE hArcData,struct RARHeaderData *D)
{
  struct RARHeaderDataEx X;
.
.
.
}
```

It uses RARHeaderData structure that has max. 260 chars for file name... Is it causes the issue?

**Comment by jyhpsycho** [comment] 2015-12-19 12:32
libunrar provides newer RARReadHeaderEx() function which uses RARHeaderDataEx instead of RARHeaderData. But, it also has max. 1024 chars for file path. Is it really sufficient for filesystem-like behavior? It seems to be need more consideration...

**Comment by jyhpsycho** [comment] 2015-12-19 12:44
OK, replacing all RARHeaderData to RARHeaderEx on rar2fs.c seems to be possible fix for this issue, though it's still have 1024 chars max. path name. I'll attach the patch.

[rar2fs_read_header_ex.patch.zip](https://github.com/hasse69/rar2fs/files/67475/rar2fs_read_header_ex.patch.zip)

**Comment by jyhpsycho** [comment] 2015-12-19 12:47
If it's not enough, there's no way for extend it without 'stealing' from libunrar source code like some function of dllext.cpp...

**Comment by hasse69** [comment] 2015-12-19 12:48
In extract_rar() the wrong function is used. It should use the Ex variant for reading header. But I changed that and it still does not work. I suspect that RARProcessFile() deep inside suffers from some path restriction. 1024 should be enough in your case but it still does not work so somewhere I suspect it hits a 260 limit anyway. This needs further investigation before I can report a bug upstream.

**Comment by jyhpsycho** [comment] 2015-12-19 12:50
Yep, you're right. it does not work with the archive what I found this issue... There's need to more investigation.

**Comment by jyhpsycho** [comment] 2015-12-19 12:52
Hmm? It's worked, too. but it's very slow for reading data... I'll remove debug messages and retry.

**Comment by jyhpsycho** [comment] 2015-12-19 12:56
It's still very slow, but file data is correctly dumped for all of my case.

**Comment by jyhpsycho** [comment] 2015-12-19 13:16
The slowness is not rar2fs' issue. It's just an issue of page cache on linux itself. Sometimes the application running my machine is not responsible due to large amount of memory on system. I guess that it needs some time for searching page cache can invalidate. Can you perform the test with current master(1.21.2) and just apply my patch, please?

**Comment by hasse69** [comment] 2015-12-19 16:06
I will. I am rather offline right now so I have not been able to check your patch. It's strange though since I believe I tried something similar to what you described but it did not resolve the problem with your attached archive?

**Comment by jyhpsycho** [comment] 2015-12-19 16:10
OK, I'll try once more using attached archive and report the result.

**Comment by jyhpsycho** [comment] 2015-12-19 16:14
It works with all of 2 sample archives I provided, and the original archive I find out this issue.

**Comment by jyhpsycho** [comment] 2015-12-19 16:19
It's also work with third testcase I attached below. It has only japanese characters for pathname, 521-byte-long in UTF-8 including slash.

[TEST.zip](https://github.com/hasse69/rar2fs/files/67520/TEST.zip)

**Comment by hasse69** [comment] 2015-12-19 17:05
Great! I will apply your patch as soon as I get online and we can close this issue! Thanks for your help in testing this.

**Comment by jyhpsycho** [comment] 2015-12-20 06:14
In addition, Is RARHeaderDataEx structure is supported by all libunrar version? If it's not, there's need to some compile-time check...

**Comment by hasse69** [comment] 2015-12-20 17:15
Yes, your patch seems to be fine.
I will apply it and push a new version.

**Closed** 2015-12-20 17:33 UTC
Labels: Type-Defect
