### ISSUE TITLE
Faulty detection  of media length

### ISSUE THREAD

**Issue by Night1** [hasse69/rar2fs#66] opened 2017-01-21 17:12 UTC
Hey,
This is not a precipitant  issue but it is reacquiring, over the past few months I have detected that some media regardless of which filesystem it is from be it NTFS or ext3/4. Is showing up as length in several hundred hours, only way to correct this is by umounting  the effected fuse mountpoint and remouting it. 

my mount settings are 
rar2fs -o allow_other --seek-length=2 /mnt/8TB02202016 /opt/rar2fs/movies

**Comment by hasse69** [comment] 2017-01-21 18:46
Thanks for the issue report.
Unfortunately I am not really sure what to do with it :(
rar2fs does not know anything about "media length", the length is most likely the result of some media player trying to extract such information from file itself.
What we can start with is getting an example of what files you have issues with.
Is it always the same file? Does it seem to be random? If you have an example of a file for which the  media player seems to report an incorrect length, is it in store on compressed format?
Also, can you in that case send a pointer to the subjected archive in mail to me?
As you understand there are a lot of things that may go wrong here, it might not even be something rar2fs is in control of.

**Comment by Night1** [comment] 2017-01-21 21:18
Hey thank you for response, I can post back with a detailed report next time i see it, and mail you header  along  with avprobe output.
As for your questions, No nothing is compressed,  player is both MPC-HC and Plex, I use Plex for the most part, which is where file is reported to be sometimes over 1000 hours long.  I have yet to see this issue reaccure on files already in a mountpoint only when adding new. 

99% of the files I have seen it as of now are mkv with x264/5 encoding and  2-3 .mp4.  
I'll keep you posted.

**Comment by hasse69** [comment] 2017-01-21 21:52
Ah, yes. I think I know what it is you are observing. The only problem is; I have no cure for it :(
PLEX is using inotify to detect changes to your media library. If you wish for PLEX to automatically detect new media in the library you need to write the files to the mounted file system, not the back-end fs. Right?
The problem here is RAR volumes! PLEX will detect a change as soon as you write the first file of the volume and will try to scan it for media info. But, at this point not all files may be available yet and thus the read-out will try to access data in files that does not exist and this can cause unexpected behavior. It seems in this case that media length information becomes invalid. You can experiment with this and turn off the automatic detection and do manual scans instead. My guess is your problem will go away.

**Comment by Night1** [comment] 2017-01-21 22:02
I allready do manual scans, and i make sure that files are 100% pass with cksfv prior to running scans, so it " should" not be an applicable case in this mater, and with a quick umount and remount corrects this issue at once (reanalyze). 
Reanalyze does nothing prior to remouting.  

Plex never writes or changes any files neither by design, and permissions are set up  to dissalow any change to folders.  

Is there any negligible delay from a rar archive beeing added to it being accessible from rar2fs?

But non the less this is an awesome product, just this one thing at times drives my crazy having to ssh in to server and run my scrips, sometimes killing streams.

**Comment by hasse69** [comment] 2017-01-22 01:10
Nope, no delay. But there is obviously something that makes the file content to not read-back properly.
But I cannot for sure tell if this is a rar2fs problem or something in the FUSE framework, For that more information is needed. Can you try to dispose of the cache once this happens instead of re-mounting?
You can invalidate the entire cache by sending the main rar2fs pid a USR1 signal (kill -USR1 <pid>)

**Comment by Night1** [comment] 2017-01-22 04:16
Will do, I'll keep you updated. thank you

**Comment by uksparky** [comment] 2017-02-01 09:17
I can also confirm this potential issue. Trying to dispose of the cache with USR1 signal did not help, unmounting and remounting with the same options was the only way to fix the proper reading of the media info.

**Comment by hasse69** [comment] 2017-02-01 09:52
Ok, thanks for the input.
Can you also try this instead of unmounting?
echo 3 > /proc/sys/vm/drop_caches
It seems this could be related to something being cached improperly. I can see no reason why media length should otherwise be reported wrong. Again, rar2fs has no knowledge of what it reads and that multiple reads would return different results is very unlikely. If the media length is initially reported correctly and then suddenly not sounds really strange.

**Comment by hasse69** [comment] 2017-02-01 23:51
If dropping the caches does not help, then please try to use the '-o direct_io' mount option.
That will effectively make any reads to go through rar2fs, by-passing any caches on the way. Performance might take a punch or two but at least it should clearly show if this is really a rar2fs problem or something else.

**Comment by hasse69** [comment] 2017-02-02 08:37
Just for info, I happened to see this today too on a file that was not even contained in a RAR!
PLEX reported the media duration to be of 496h, but the .avi/MPEG4 length was reported correctly at 1.31h.
I really doubt this has anything to do with rar2fs, this seems more like a bug in PLEX, especially since this is a plain file which more or less is handled transparently by rar2fs.

**Comment by Night1** [comment] 2017-02-04 11:41
I also thought so, however I did try to restart my plex service to no effect. But remouting rar2fs mountpoints works. 

I have not seen this issue latly, but I have not added much content either.

**Comment by hasse69** [comment] 2017-02-04 12:00
What needs to be triggered is a completely new indexing. If a file system is unmounted while the server is running that might trigger such. Just restarting the server on the other hand might not.
I clean restart of the server might not cause the library to become  "dirty" but a change in the mount point while being monitored will for sure. I currently have no reason to believe this being a problem in rar2fs, but let's keep this under observation.

**Comment by Night1** [comment] 2017-02-04 18:12
Makes sense, Current setup for rar2fs and my plex is Intel i7 990x with 32GB of ram, I do monitor loads,  I have not seen load spikes on cpu/mem. 

I can add some logging to I/Os to see if that might cause this. 
non the less thank you for looking in to this :), Not alwyas when I'm on the run I am able to get keys to login to my server to remount.

**Comment by KyleSanderson** [comment] 2017-02-06 19:32
@night1 this is an old issue. If you list the archives before all chunks are present, it's cached somewhere internally and you do indeed have to restart rar2fs. I usually just kill irssi and restart my box because it's easier that way; but this constantly happens.

**Comment by hasse69** [comment] 2017-02-06 21:00
I did not really get this? Old issue where? In rar2fs?
To be honest I have seen nothing really pointing to an issue in rar2fs here. If you have some more information I can look into it. But if this was a cashing issue in rar2fs then an invalidation of the cache should help in combination with a rescan of the media. From what I know that did not help. 

If media is accessed before all volume files are present the data is not available and all 0 will be returned. This might be cached by the OS, but nothing is cached in rar2fs related to file contents.
If the wrong data is cached in kernel then invalidation of it should help (see previous post) also here in combination with a rescan, but I guess that is obvious. Another thing to try is the direct_io mount option that will force all reads to be sent to rar2fs, i.e. effectively by-passing the page cache. Then a later rescan should pick up the correct information.

**Comment by KyleSanderson** [comment] 2017-02-06 21:55
https://github.com/hasse69/rar2fs/issues/50#issuecomment-227088330 this entire thread. Hopefully the recent MP changes help fix the performance issues; looking forward to that new release being tagged.

**Comment by hasse69** [comment] 2017-02-06 22:50
Yes fine, but according to what I just said, if this problem is really related to reading data too soon the actions I have listed should help isolate the problem to indeed be cache related. I have no such confirmation as of yet.
That this problem is related to cache issues is simply based on a hunch, at least from my side.
And the fact that if this indeed *is* cache related, it is not much rar2fs can do about it, because it is not the cache in rar2fs that results in invalid data being returned. I am not sure how rar2fs could ever prevent this from happening safely. If data does not exist (due to a volume missing) it hardly can sit in a corner and wait for something that might never happen.

**Comment by KyleSanderson** [comment] 2017-02-07 09:36
@hasse69 shouldn't watching inotify resolve this entirely? If a raw smb share shows there to be no issue, and somehow fuse + rar2fs shows absolute corruption; the issue is obviously with rar2fs which absolutely depends on fuse?

**Comment by hasse69** [comment] 2017-02-07 09:47
Watching inotify? It is PLEX (or whatever client) that watches the mount point using inotify and when it sees a file being added it starts to read from it. Again, a guess from my side. There is nothing rar2fs can do here besides possibly detect writes to the file system and delay any access to it until last volume file is written. However, since rar2fs cannot possibly know if all volume files are supposed to be written I see this as a complete dead end. If this is really the case, then a periodic scanning instead of event triggered should minimize the chance of this ever happening, right?

**Comment by KyleSanderson** [comment] 2017-02-07 09:50
Again, this is absolutely reproducible without Plex. Viewing the binary
output from the fuse filesystem reproduces the issue.

**Comment by uksparky** [comment] 2017-02-07 10:08
I have seen this too, when I had a media that was unplayable and was 
showing with an incorrect playback length time then at first I assumed 
it was just that particular media file. So I tried mkvinfo on the media 
and received an error about no or invalid EDML header present (or 
something along those lines). Remounting the rar2fs mount then gave the 
correct info via mkvinfo as well as an analyze in plex allowing the 
media to be played correctly.

I've disabled library update on filesystem changes and have gone to a 
scheduled refresh to see if this helps at all. I think I commented that 
dropping the caches didn't help. The next step was to try with direct 
I/O enabled.

**Comment by hasse69** [comment] 2017-02-07 10:40
@KyleSanderson Reproduces what? If you read something directly from the mount point after data has already been cached improperly, yes of course it will. 
If you on the other hand never accessed the data before and know all volumes are there and it still returns invalid information, yes then there is a problem here somewhere.

**Comment by hasse69** [comment] 2017-02-07 10:55
Btw, do you see this for both new and old style archives? For old style (.rNN) format I guess there might an issue since there is a chance main archive (.rar) could be written last. For new style archives that should not be the case. If wrong volume data is cached in rar2fs the an invalidation of the cache and also the page cache should help.

**Comment by hasse69** [comment] 2017-02-07 11:08
Ok, I do see an issue in the code here. If I remove the main .rar archive in an old style volume, the file still pops up! That is definitely wrong and will result in wrong volume offsets. Here rar2fs should not allow the contents of those files to be displayed until at least the first volume file is written.

**Comment by hasse69** [comment] 2017-02-07 18:52
Some update.
It was possible to reproduce this rather easily. It affects both old and new style archives the same.
Simply by removing the first file in the volume before mounting and then access the file and after that putting the missing file back. All reads were messed up! Then, after invalidation of the rar2fs cache still no change (as I expected) *but* after also invalidating the page cache data was read back correctly again.

**Comment by KyleSanderson** [comment] 2017-02-07 20:07
Great news!

Would it be possible to use inotify to listen to cached files for writes,
and when they're opened or closed for writing force a cache invalidation?
Otherwise maintaining the cache should be perfectly fine as the underlying
inodes are guaranteed to have zero writes against them. Honestly; I'd give
up a couple hundred megs of RAM for this even though that's incredibly
excessive.

**Comment by hasse69** [comment] 2017-02-07 20:38
I am not really sure how inotify would help here?
If you write files through the mount point rather than the source directory the internal cache in rar2fs is maintained already. The problem is the page/dentry/inode cache in the kernel. I know of no API to drop entries from the cache based on pure path names. Possibly the low level FUSE API that operates on inodes might have options here. But rar2fs is written on top of the high level API. 
But if rar2fs does not allow display of files until a minimum set of volume files exists then I do not think this is a problem. 
There is another discussion regarding inotify and watching the source folder for changes in a portable way (performance reasons) in issue #32.
Adding inotify directly to rar2fs is something I would like to avoid for several reasons.

**Comment by Night1** [comment] 2017-02-07 21:17
Plex does use inotify to find new files, perhaps partials fails are detected as rars are beeing added?

**Comment by KyleSanderson** [comment] 2017-02-08 01:46
My issue atleast is through something like rtorrent; the archive will be present; but be missing chunks. So if you're relying on the file simply existing; that the set becomes valid, this is not always true.

**Comment by hasse69** [comment] 2017-02-08 06:22
If there are chunks missing you will get header corruption or worse. So that will be equal to file not being there.

**Comment by hasse69** [comment] 2017-02-09 07:35
Given the rather delicate process of handling incomplete/corrupt archives, there will be two changes made for addressing this issue. First of all, the kernel cache will be disabled. It comes with a performance penalty but I think it is better data is read from actual source every time rather than being incorrectly cached.
Secondly the first archive in a volume *must* always exists (at least the header) for proper offset calculations of data before a file should be visible in the mount. With these two changes I think a lot of the problem you see will go away. But there are no guarantees, simulating a file system on top of RAR files has some implications that are hard to program around.

**Comment by uksparky** [comment] 2017-02-09 09:29
Sounds good to me hasse69, good job!

**Comment by Night1** [comment] 2017-02-09 20:02
Great work!

**Comment by hasse69** [comment] 2017-02-09 22:44
Try this patch on master/HEAD

[patch.txt](https://github.com/hasse69/rar2fs/files/765179/patch.txt)

It still needs some polishing and I need to add a header check to make sure first volume file has proper data. But even without that I think this patch will reduce the chance of this problem occurring.

**Comment by hasse69** [comment] 2017-02-09 23:35
This one also checks the header

[patch.txt](https://github.com/hasse69/rar2fs/files/765275/patch.txt)

**Comment by Night1** [comment] 2017-02-11 09:59
Will this be trickled down in to a release?

**Comment by KyleSanderson** [comment] 2017-02-11 10:19
Eventually. That's honestly what I'm pinned on with this repo. I use
archive2fs but it's a memory waste atm (and I haven't shipped it).

On 11 Feb 2017 1:59 am, "Night1" <notifications@github.com> wrote:

Will this be trickled down in to a release?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hasse69/rar2fs/issues/66#issuecomment-279133898>, or mute
the thread

**Comment by hasse69** [comment] 2017-02-11 10:27
At some point yes. But there are way to many open issues right now.

**Comment by hasse69** [comment] 2017-02-11 10:34
archive2fs? So if you feel you have something better than this why waste time on rar2fs? Sorry, do not get it!

**Comment by KyleSanderson** [comment] 2017-02-11 10:41
Working on a prototype does not provide absolution, nor fix the issues
related to the "grandparents" for a solution. Regardless of solution, the
inspiration comes from rar2fs.

**Comment by hasse69** [comment] 2017-02-11 10:49
Sure. As long as you can hopefully spare some time assisting me in testing what ever you report I am fine with whatever.

**Comment by hasse69** [comment] 2017-02-11 10:57
@KyleSanderson Btw, I guess it is a good thing you got *inspired* by rar2fs :) I hope you did not get too inspired though because if I would have written something like this today there a lot of things I would probably have done differently.

**Comment by hasse69** [comment] 2017-02-11 11:55
Any feedback on how this patch is working out?

**Comment by Night1** [comment] 2017-02-11 12:07
Been far to long since  I built from source, struggling to build without ./configure

**Comment by hasse69** [comment] 2017-02-11 12:11
What system are you on that does not provide autotools?

**Comment by Night1** [comment] 2017-02-11 12:29
/rar2fs# autoconf
configure.ac:9: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:13: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:27: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:481: error: possibly undefined macro: AM_ICONV


I get that with autconfi, it does

**Comment by uksparky** [comment] 2017-02-11 12:31
I got the same as that, had to install libtool package. Once I did that I'm now getting the following from automake:

~/rar2fs$ automake
configure.ac:7: error: required directory ./config does not exist
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.

**Comment by hasse69** [comment] 2017-02-11 12:33
autoreconf -fi, that gives what?
I can upload a tarball here with the patch applied if that helps.

**Comment by hasse69** [comment] 2017-02-11 12:35
All you should need to do in the rar2fs source folder is

autoreconf -fi
./configure ...

**Comment by uksparky** [comment] 2017-02-11 12:47
All built and installed now. Going to try chucking some media at it and 
a load of library updates, see how it goes...

**Comment by hasse69** [comment] 2017-02-11 12:57
So autoreconf worked as expected, or? You should run autoreconf -f to regenerate meta files according to your currently installed version of autotools.

Anyway, it is now going to boil down to a new problem,,,
If the server detects a change in the watched folder, but rar2fs will not allow the the file to display, question is how clever the server is. There might be a slight chance the server will give up thinking the folder contained nothing interesting. Lets see. What I possibly could do is to modify the timestamp on the outer folder once rar2fs accepts whatever is inside the RARs. Would that make sense? And would that trigger the watch? I am not sure...

**Comment by Night1** [comment] 2017-02-11 12:58
ah missed the reconf, it is running now. I'm also moving around lots and lots of data lets see if it can provoke a response

**Comment by hasse69** [comment] 2017-02-11 12:59
@Night1 @uksparky Maybe you should read the Wiki at some point? I have a slight recollection of this being described there :P

**Comment by Night1** [comment] 2017-02-11 13:06
@hasse69  lies! you just added that :P 

I still think you are awesome!

**Comment by hasse69** [comment] 2017-02-19 09:05
Any news here regarding test of the patch? Any difference in behavior or not?

**Comment by KyleSanderson** [comment] 2017-02-19 09:31
I'm crazy abstracted now with sshfs and kin, I can't provide usable
feedback but if people and yourself are reporting better handling with
corrupt archives that bodes well for all of us.

**Comment by hasse69** [comment] 2017-02-19 12:13
That is ok. However, since I do not experience this issue myself I rely on others to report back their findings.
This patch really has nothing to do with corrupt archives but rather that the store mode volumes files are processed in a order that guarantees correct offset calculations.

**Comment by uksparky** [comment] 2017-02-19 14:35
I’ve not experienced any bad length and badly cached data for any of my info since implementing this patch, looks to work perfectly to me!

Cheers

**Comment by Night1** [comment] 2017-02-19 16:12
Ok. been able to test some now, loooks like some other issue now, I have yet to see the length issue not it is not detecting anything, when I navigate to folder in mountpoint I do find folder and sfv but no .mkv/mp4.

**Comment by hasse69** [comment] 2017-02-19 17:30
Well are you sure all parts are there? Do you see any .rar files instead of .mkv/mp4?

**Comment by hasse69** [comment] 2017-02-19 21:46
@Night1 I see no reason why this patch should have the described effect. Sure, there is a slight possibility that a client that only monitors a folder for changes might not pick up the file if no retries are made, but not if you list the folder manually from the mount point itself, especially not if all files are present and contains valid headers. If you are using the --seek-length option try to remove that to see if it makes any difference. It is the only thing I can honestly think of could have any effect such as the one you describe.

**Comment by hasse69** [comment] 2017-03-03 19:27
Any updates here? I would like to merge the latest patch but without getting more feedback it seems too risky...

**Comment by Night1** [comment] 2017-03-06 21:26
I am happy with the changes, works fine for me :) thank you very much

**Comment by Jonher937** [comment] 2017-03-08 21:05
This seems to fix the duration problems in Plex. After a compile of rar2fs from master a refresh in Plex fixes the time. Thanks!

**Comment by hasse69** [comment] 2017-03-08 21:39
Thanks for the feedback! It sounds to me like the patch at least does not make things worse. I will merge it to master and then close this issue.

**Closed** 2017-03-08 22:34 UTC
Labels: Defect, Priority-Medium
