### ISSUE TITLE
Rar2Fs unmounts after few seconds on Dokany v1.2.1

### ISSUE THREAD

**Issue by Gargauth** [hasse69/rar2fs#106] opened 2019-02-27 19:23 UTC
I compiled Rar2Fs with cygwin with Dokany v1.2.1.2000 and I am experiencing issue where mounted volume disappears (after around 60 seconds). Furthermore even Ctrl-C does nothing to terminate the process. There's no such issue with Dokany v1.2.0.

```
$ uname -a
CYGWIN_NT-10.0 DESKTOP-10S5EHE 3.0.1(0.338/5/3) 2019-02-20 10:19 x86_64 Cygwin
$ gcc --version
gcc (GCC) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I installed rar2fs using these steps:

```
cd /
wget https://github.com/hasse69/rar2fs/releases/download/v1.27.1/rar2fs-1.27.1.tar.gz
tar -zxvf rar2fs-1.27.1.tar.gz
cd /rar2fs-1.27.1
wget https://www.rarlab.com/rar/unrarsrc-5.7.3.tar.gz
tar -zxvf unrarsrc-5.7.3.tar.gz
sed s/-fPIC//g -i unrar/makefile
make -C unrar lib
wget https://github.com/dokan-dev/dokany/releases/download/v1.2.1.2000/dokan.zip
unzip dokan.zip
chmod -R 777 x64
cp x64/Cygwin/cygdokanfuse1.dll /usr/bin
cp -R x64/Cygwin/lib/* /usr/lib
cp -R x64/Cygwin/include/* /usr/include
./configure
make
make install
```

I don't know inner workings of how this all works, but considering the mounted volume disappears just after few seconds, I suspect this issue could have something to do with following change in v1.2.1.1000 (https://github.com/dokan-dev/dokany/releases/tag/v1.2.1.1000):

> Moreover, this version use a new mechanism of keepalive between the FS userland application and the driver. Instead of having a ping every X secondes. The Dokan library will now open a handle on the driver FS and close it (wanted during unmount or unwanted during a crash) to release the driver. This creates a better stability on FS userland crash and makes the unmount event faster.

**Comment by hasse69** [comment] 2019-02-27 19:53
Thanks for the issue report.
I am not sure how this really boils down to an issue in rar2fs? A FUSE file system such as rar2fs is completely unaware of the actual backend being used. Please run the mount in the foreground using the -f or -d flag and report back what FUSE/rar2fs says at the moment it is unmounted.

**Comment by hasse69** [comment] 2019-03-03 11:12
Any updates here?

**Comment by Gargauth** [comment] 2019-03-03 13:07
Sorry, I'm away from my computer for the weekend. I'll try to reproduce it once again when I get back and have free time. However, I ran rar2fs with debug and foreground flag and I remember that there was following error line every time it happened:

Ioctl failed for wait with code 995.

Also I don't know if this may be related, but any unmount (whether forced with Ctrl-C or on its own when it disappeared) made rar2fs hang indefinitely. This did not occur on previous Dokany version. I encountered some additional issues even with previous Dokany versions and decided to go with handling rar2fs through linux virtual machine instead.

**Comment by hasse69** [comment] 2019-03-03 17:11
That error message is not coming from rar2fs, it must be something originating from the FUSE emulation layer. I suspect you would see similar issues with other FUSE file systems, not only rar2fs, I have had reports about Dokany not being very stable before. There is an alternative FUSE emulation layer for Windows called WinFSP. I suggest you try also that for comparison.

**Comment by hasse69** [comment] 2019-03-21 19:27
A quick google sent me in this direction
https://github.com/dokan-dev/dokany/issues/433
Anything that looks familiar?

**Comment by Gargauth** [comment] 2019-03-21 19:58
I ended up switching to Linux VM instead of dealing with Windows drivers/cygwin. Unfortunately I don't have knowledge or time to track this issue down and help resolve it (if it's even rar2fs fault, and not dokany's). So feel free to close this issue, although it can still be relevant to somebody who's building rar2fs on cygwin using latest dokany backend.

**Comment by hasse69** [comment] 2019-03-21 20:06
That a new version of Dokany suddenly starts to fail indicates an issue in Dokany rather than rar2fs. There might of course be something that can be tracked back to rar2fs or worked around but unless I can get detailed information on what exactly they changed and how it can affect a FUSE file system like you describe there is not much I can do I am afraid. I agree that this is valuable information to others trying to use rar2fs in combination with Dokany v1.2.1, but on the other hand until we see more users having the same problem as you reported, it might even be something in your local environment.
I will try to find some time to install Dokany 1.2.1 myself. Possibly I can dig deeper into the problem if I can reproduce the issue.

**Comment by hasse69** [comment] 2019-03-21 21:53
I wonder if this is not actually the solution to your problem?
https://github.com/dokan-dev/dokany/releases/latest

**Comment by hasse69** [comment] 2019-03-22 18:21
I will close this issue since it seems Dokany made a new release resolving the bug.
Please confirm that this new version of Dokany works as expected.

**Closed by hasse69** 2019-03-22 18:21 UTC
