### ISSUE TITLE
Cannot listing files in archive created with -ep2 option

### ISSUE THREAD

**Issue by jyhpsycho** [hasse69/rar2fs#68] opened 2017-02-05 03:03 UTC
The issue which is observed during issue #49 is finally reproduced, which blocks testing patch some time (see https://github.com/hasse69/rar2fs/issues/49#issuecomment-272450364).

* HOW TO REPRODUCE:
 1) Create sample(Working directory is /dev/shm/TEST on this case).
```
$ dd if=/dev/urandom of=TEST1 bs=256 count=1
$ dd if=/dev/urandom of=TEST2 bs=256 count=1
$ rar a -m5 -ma5 -mt1 -ep2 TEST.rar TEST1 TEST2
```
 2) Mount and try to list.
```
$ mkdir X
$ rar2fs --flat-only --show-comp-img -o ro,allow_other TEST.rar X
$ ls -lAR --full-time X
```
* EXPECTED RESULT:
```
X:
total 8
-rw-r--r-- 1 rar_work users 1024 2017-02-05 11:43:21.240547106 +0900 TEST1
-rw-r--r-- 1 rar_work users 1024 2017-02-05 11:43:23.090505706 +0900 TEST2
```
* ACTUAL RESULT
```
X:
total 0
```

* Additional information:
```
$ /dev/shm/rar2fs/rar2fs --version
rar2fs v1.23.1-git819a696 (DLL version 7)    Copyright (C) 2009 Hans Beckerus
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under
certain conditions; see <http://www.gnu.org/licenses/> for details.
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```
```
$ unrar vta TEST.rar 

UNRAR 5.40 freeware      Copyright (c) 1993-2016 Alexander Roshal

Archive: TEST.rar
Details: RAR 5

        Name: dev/shm/TEST/TEST1
        Type: File
        Size: 1024
 Packed size: 1024
       Ratio: 100%
       mtime: 2017-02-05 11:43:21,240
  Attributes: ..A....
       CRC32: DDA8339D
     Host OS: Windows
 Compression: RAR 5.0(v50) -m0 -md=128K

        Name: dev/shm/TEST/TEST2
        Type: File
        Size: 1024
 Packed size: 1024
       Ratio: 100%
       mtime: 2017-02-05 11:43:23,090
  Attributes: ..A....
       CRC32: 01511C2B
     Host OS: Windows
 Compression: RAR 5.0(v50) -m0 -md=128K

     Service: EOF
```

Note that it stores full path except drive letter. It's what `-ep2` option does. This is default behavior if the archive is created using absolute path to specify input files. For the case of using relative path, it does not occur.

I'll attach the sample. [TEST.zip](https://github.com/hasse69/rar2fs/files/752713/TEST.zip)

**Comment by jyhpsycho** [comment] 2017-02-05 03:09
With `-ep3` option, it also includes driver letter, and it does not work like `-ep2`. The result of unrar on this case is:
```
$ unrar vta TEST.rar

UNRAR 5.40 freeware      Copyright (c) 1993-2016 Alexander Roshal

Archive: TEST.rar
Details: RAR 5

        Name: Z_/dev/shm/TEST/TEST1
        Type: File
        Size: 1024
 Packed size: 1024
       Ratio: 100%
       mtime: 2017-02-05 11:43:21,240
  Attributes: ..A....
       CRC32: DDA8339D
     Host OS: Windows
 Compression: RAR 5.0(v50) -m0 -md=128K

        Name: Z_/dev/shm/TEST/TEST2
        Type: File
        Size: 1024
 Packed size: 1024
       Ratio: 100%
       mtime: 2017-02-05 11:43:23,090
  Attributes: ..A....
       CRC32: 01511C2B
     Host OS: Windows
 Compression: RAR 5.0(v50) -m0 -md=128K

     Service: EOF
```

**Comment by jyhpsycho** [comment] 2017-02-05 03:17
I think that it's difficult to distinguish the path name is included by real contents(relative path) or base path of it. Thus the expect result is one of which suggested above(ideal), or at least:
```
$ ls -lAR --full-time X
X:
total 0
drwxr-xr-x 3 rar_work users 60 2017-02-05 12:14:37.947352585 +0900 dev

X/dev:
total 0
drwxr-xr-x 3 rar_work users 60 2017-02-05 12:14:45.599150489 +0900 shm

X/dev/shm:
total 0
drwxr-xr-x 2 rar_work users 80 2017-02-05 12:15:20.092239475 +0900 TEST

X/dev/shm/TEST:
total 8
-rw-r--r-- 1 rar_work users 1024 2017-02-05 11:43:21.240547106 +0900 TEST1
-rw-r--r-- 1 rar_work users 1024 2017-02-05 11:43:23.090505706 +0900 TEST2
```

**Comment by jyhpsycho** [comment] 2017-02-05 03:26
I found the difference!
```
$ unrar vta TEST.rar

UNRAR 5.40 freeware      Copyright (c) 1993-2016 Alexander Roshal

Archive: TEST.rar
Details: RAR 5

        Name: dev/shm/TEST/TEST_DIR/TEST1
        Type: File
        Size: 1024
 Packed size: 1024
       Ratio: 100%
       mtime: 2017-02-05 11:43:21,240
  Attributes: ..A....
       CRC32: DDA8339D
     Host OS: Windows
 Compression: RAR 5.0(v50) -m0 -md=128K

        Name: dev/shm/TEST/TEST_DIR/TEST2
        Type: File
        Size: 1024
 Packed size: 1024
       Ratio: 100%
       mtime: 2017-02-05 11:43:23,090
  Attributes: ..A....
       CRC32: 01511C2B
     Host OS: Windows
 Compression: RAR 5.0(v50) -m0 -md=128K

        Name: dev/shm/TEST/TEST_DIR
        Type: Directory
       mtime: 2017-02-05 12:19:32,484
  Attributes: ...D...
       CRC32: 00000000
     Host OS: Windows
 Compression: RAR 5.0(v50) -m0 -md=0K

     Service: EOF
```

As you can see, the header entry of base path is not included. More precisely, The header entry of `TEST_DIR` is included on archive, `dev/shm/TEST` is not.

**Comment by hasse69** [comment] 2017-02-05 07:32
Yes, I am aware of this difference. Some archives does not have an entry for the base dir until in the end. I compensate for that but only for /.
I am not sure how using absolute paths really match well with a file system, to me it does not make much sense to support it. The paths are expected to be relative to the mount point. Too much logic for a very narrow use case if you ask me. But I will check how much work it is.

**Comment by hasse69** [comment] 2017-02-06 10:31
Does not seem to be that much work to fix this. Will look into it.

**Comment by hasse69** [comment] 2017-02-07 00:29
Try this patch.

[patch.txt](https://github.com/hasse69/rar2fs/files/756219/patch.txt)

For some reason adding your TEST.rar file inside another RAR does not work.
Something seems different also when archives like this is added inside another archive.
I do not have time to dig into that, so for now abs paths in RAR is not supported for embedded RARs.
If that is needed, stack your file systems instead. That works just fine.
I very close to removing the built-in support for embedded archives because it is limited in functionality and makes the code complex and error prone. Stacking is a much better approach for this.

**Comment by hasse69** [comment] 2017-02-07 00:38
[patch.txt](https://github.com/hasse69/rar2fs/files/756239/patch.txt)

**Comment by jyhpsycho** [comment] 2017-02-07 15:43
Yeah, it seems to work. Thanks :-)

I agree with your opinion; In fact, I'm always use --flat-only option, which disables parsing embedded RAR. It operates unwanted way for me. I think that 'stacking' is more general way to treat archive-in-archive than nested parsing.

**Comment by hasse69** [comment] 2017-02-07 17:44
Thanks for trying it out, but unfortunately regression failed for e.g. issue42.
This patch needs some more work.

**Comment by hasse69** [comment] 2017-02-07 18:44
Try this one instead

[patch.txt](https://github.com/hasse69/rar2fs/files/758660/patch.txt)

**Comment by jyhpsycho** [comment] 2017-02-08 20:43
Good, I found the regression after testing on normal use case :-( Now it works with sample archive, generated one with volume option(both of header encryption is enabled or not), and one of normal use case for me.

**Comment by hasse69** [comment] 2017-02-08 21:56
Thanks, I will release this patch then and close the issue.

**Closed** 2017-02-08 22:16 UTC
Labels: Defect, Priority-Low
