### ISSUE TITLE
Stacking rar2fs for use inside LXC-container

### ISSUE THREAD

**Issue by tumd** [hasse69/rar2fs#84] opened 2017-10-31 18:34 UTC
Hi,

First of all, thank you so much for great work on this project. I really appreciate it!

However, I do have an issue since I upgraded rar2fs to a version where [the stacking was removed](https://github.com/hasse69/rar2fs/commit/eb8bfe9c48dd035d3af3025ffc53e718552c24a0).

I use LXC/LXD to containerize plex and other applications into their own environments. And rar2fs on the host that get bind-mounted to containers - because the lxc-containers cannot (at this time) run the fuse on their own. 
With only one rar2fs layer, a container running Plex has no problem using it. And it's quite snappy too. 
But when I try to stack two rar2fs mounts on top of each other to mimic the functionality pre https://github.com/hasse69/rar2fs/commit/eb8bfe9c48dd035d3af3025ffc53e718552c24a0 I encounter issues. Starting a container with plex and the the second/outer rar2fs bind-mounted, everything gets crazy slow, and unusable.

I'm not sure what is causing this issues, or how to investigate this further.

**Comment by hasse69** [comment] 2017-10-31 19:43
Interesting, but the commit you are referring to was not the one removing internal support for multi-level archives? That support was removed in https://github.com/hasse69/rar2fs/commit/d8718e3a316c76ba31432f5166dc6c5d68997f1a.
That was the last commit before releasing v1.24.0. Can you please try v1.26.0 just to make sure nothing was fixed on the way here, even though I doubt it.

**Comment by tumd** [comment] 2017-10-31 20:31
Ah, I might have messed up the commits in my last post. It was https://github.com/hasse69/rar2fs/commit/d8718e3a316c76ba31432f5166dc6c5d68997f1a I was thinking of.
I'm currently running 1.25.2-38628b2. I'll try 1.26.0 tomorrow, but I too doubt it has been fixed there.

**Comment by hasse69** [comment] 2017-10-31 21:49
Right, that makes more sense. It is better you run this on latest version so that we are aligned.
I do not really expect any difference in behavior. 
How do you mount your first level? Do you use `--seek-length=1` or similar? If not, try that.
Also, I am a bit unsure about what PLEX is actually pointed to. I assume you point it to the second mount. There is obviously some penalty involved by stacking FUSE file systems, but it should not be as significant as you describe. For single level archives it should hardly be noticeable at all since it basically becomes pass-through only for the second level.

**Comment by hasse69** [comment] 2017-11-01 19:30
I am finding it hard to believe that the apparent slow-down is caused by a pure bug. It would be very interesting if you could test a stacked setup locally not involving the LXC. Do you see the same thing?
I can not remember observing any major performance issues myself using the stacked approach. In fact, stacking FUSE file systems is a rather common use-case, e.g. rar2fs over encfs or similar combos.

Could this be related to some access rights or visibility? When you bind mount your second level mount point only, it will still try to access the first level and if done from within the container could this yield some restrictions? What if you first bind mount the first level and then mount your second level on top of the bind mount and then bind mount also the second level? Basically making both mount points visible to the container? Would it make any difference? Basically I am a bit clueless about this one so consider this an initial brain-dump only ;) I am probably completely off track...

**Comment by tumd** [comment] 2017-11-01 20:45
Hmm. I'm a bit baffled. Now I think it works without massive lag.

This is what the mounts looks like now;
`rar2fs /data/media /data/flat-media -o rw,allow_other,uid=1000,gid=112,dev,suid`
`rar2fs /data/flat-media /data/flatter-media -o rw,allow_other,uid=1000,gid=112,--seek-length=1,dev,suid`

I'll try to explain what I did;
- Installed 1.26.0 over the old version.
- Stopped the plex-container
- Unmounted and mounted _only_ the second/outer layer (aka. flatter-media)
- Rearranged the mounts for the plex-container so it was the only container using 'flatter-media'
- Started the plex-container

After this, I did unmount it all, remounted and started all containers. And now the setup works on two different containers.

I'm not completely sure what solved it, but most likely I managed to mess up the container-mounts somehow (using lxd-templates to add the mounts).
So, for now I see my issue as resolved. :)

Btw, what are the correct way to include an rar2fs argument in fstab?
Right now it looks like this;
`rar2fs#/data/media /data/flat-media  fuse allow_other,uid=1000,gid=112 0 9`
`rar2fs#/data/flat-media /data/flatter-media  fuse allow_other,uid=1000,gid=112,--seek-length=1 0 10`

**Comment by hasse69** [comment] 2017-11-01 20:55
Glad to hear it suddenly started to work for you.
But why do you use `--seek-length=1` on the second level mount point (`flatter-media`)? I do not think you have that many RAR volumes in the second level? I think most is gained by having the `--seek-length` option added to the first mount point (`flat-media`). The `fstab` syntax looks fine.

**Comment by hasse69** [comment] 2017-11-07 19:55
Closing this since it seems the issue can be considered solved.

**Closed by hasse69** 2017-11-07 19:55 UTC
Labels: Other
