### ISSUE TITLE
Cache Warmup

### ISSUE THREAD

**Issue by jcastilloalonso** [hasse69/rar2fs#131] opened 2020-01-08 06:20 UTC
Ideally we want to have rar2fs cache fully populated so we can quickly browse the whole mount.

Right now the only way to warm up the cache after a first mount would be to run ls -R  inside the mount and wait for rar2fs to open each rar file. This request would allow rar2fs to warm/build the cache on the background allowing for even multiple rar file reads at the same time.

Maybe we could define how many workers we want to use in the background, while still allow rar2fs to behave as usual if a particular folder is read as while it's building the cache.

**Comment by hasse69** [comment] 2020-01-08 06:46
Thanks for the improvement suggestion.
I managed to workaround the blocker in issue #124 and did some initial tests.
In those tests the warmup performs about 60-65% better than if you manually populated the cache through the file system. I willl drop a patch here later which you might try on your setup.

**Comment by hasse69** [comment] 2020-01-08 08:55
Here is a patch you can try (you need to be on `master/HEAD`),

[issue131.patch.txt](https://github.com/hasse69/rar2fs/files/4034277/issue131.patch.txt)

Some notes about the implementation
* If you wish to debug and get a timestamp for how long it takes to populate the cache in the background uncomment line 87 and rebuild. Check the syslog for output or run in the foreground using the `-f` flag.
* The improvment in cache population time from my measurements is ~66% when not using a seek length limiter and about 33% for a seek length of 1.  So not that much but better than nothing.
* The source tree walk is spawning threads on directory level. That means best performance is reached if you put all your archives/volumes in separate sub-folders rather than stashing them all in one place.
* I/O is a limiting factor and becomes a bottle neck at least for me since the CPU load is only increasing with about roughly 10-15%.

Please report back your findings.

**Comment by jcastilloalonso** [comment] 2020-01-08 18:41
Hello Hans.

I don't see any background activity scanning after applying the patch. I'm mounting rar2fs over another fuse mount so that might be related. I tried to uncomment line 87, but nothing relevant/comment was there. Could you please confirm? Thanks

**Comment by hasse69** [comment] 2020-01-08 18:59
If you run in the foreground `-f` you should see something like this provided you uncommented line 87
```
rar2fs[2364]: cache warmup initiated
rar2fs[2364]: cache warmup completed after 29 seconds
```
I does not matter if you stack mounts or not, the warmup would cannot tell the difference.
Something must have gone wrong when you applied the patch or it was not rebuilt properly afterwards.

**Comment by jcastilloalonso** [comment] 2020-01-08 19:18
Hans, I might be doing something wrong, line 87 of rar2fs.c refers to:

```
struct volume_handle {
        FILE *fp;
        off_t pos;
};

```
Here is my step by step:

```
# git clone https://github.com/hasse69/rar2fs.git
# cd rar2fs
# wget https://github.com/hasse69/rar2fs/files/4034277/issue131.patch.txt
# git apply --stat issue131.patch.txt
```

**Comment by hasse69** [comment] 2020-01-08 19:22
Yes you are doing something wrong ;)
From git apply man-page:
```
       --stat
           Instead of applying the patch, output diffstat for the input. Turns off "apply".
```

**Comment by jcastilloalonso** [comment] 2020-01-08 19:34
Now it's working. And wow it's way faster on my setup! I'll report more when it's complete.

**Comment by jcastilloalonso** [comment] 2020-01-08 20:00
The speed at which it flew by the folders was definitely faster, yet it seems the process stopped before filling the whole cache, this is what the output shows:

```
# rar2fs -f -o allow_other,ro,umask=222,--seek-length=1 /mnt/Site/ /mnt/unrar/Site/
rar2fs[28398]: mounted /mnt/unrar/Site
rar2fs[28398]: cache warmup initiated
scandir: Transport endpoint is not connected
scandir: Transport endpoint is not connected
scandir: Transport endpoint is not connected
scandir: Transport endpoint is not connected
scandir: Transport endpoint is not connected
scandir: Transport endpoint is not connected
scandir: Transport endpoint is not connected
rar2fs[28398]: cache warmup completed after 557 seconds
```
Any clue on the Transport endpoint message? Half of the folders worked great and got cached, while the rest did not. Doing the ls -R command or checking each folder does generate the cache in that particular folder.

**Comment by hasse69** [comment] 2020-01-08 20:14
The error messages indicates a problem with a FUSE mount that no longer exists.
Are you sure the other mount did not crash?

**Comment by jcastilloalonso** [comment] 2020-01-08 20:18
Interesting, I checked the other FUSE mount debug logs and there are no error entries (also had it in debug mode to see what it was happening) I also checked and both mounts still work.

**Comment by hasse69** [comment] 2020-01-08 20:30
Ok, can you reproduce? In that case let's try to get some more descriptive message when it fails.
Replace line 2652 in `rar2fs.c`
```
                        perror("scandir");
```
with
```
                        printf("scandir: failed for %s with error %d (%s)\n", root, errno, strerror(errno));
```

**Comment by jcastilloalonso** [comment] 2020-01-08 20:38
This is the error I'm seeing:

`scandir: failed for /mnt/Site/Subdir2 with error 24 (Too many open files)`

Seems it's too aggressive opening files, wonder if you can limit the number of workers?

**Comment by hasse69** [comment] 2020-01-08 20:44
Can you check your limits using `ulimit -a`.
Here is an example on my system
```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 62951
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 62951
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
Hence the low default limit set for open files (1024),
Try to change that to `unlimited` using
```
ulimit -n unlimited 65000
```

**Comment by jcastilloalonso** [comment] 2020-01-08 21:05
Updated it to 65000 as you requested. Still got the same error. 

I have a lot of files if it means anything:

```
# ls -R | wc -l
197707
```

**Comment by hasse69** [comment] 2020-01-08 21:15
Number of files does not matter really, not all of them will be opened at once.
But what you can try is to run this once you see the error message the first time
```
lsof | grep rar2fs
```

**Comment by jcastilloalonso** [comment] 2020-01-08 21:23
I got the following error from my original FUSE mount, it's getting throttled due to the big amount of file reads:
```

2020/01/08 15:20:01 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=316539375982, userRateLimitExceeded)
2020/01/08 15:20:01 DEBUG : pacer: Rate limited, increasing sleep to 1.550705988s
2020/01/08 15:20:02 DEBUG : pacer: Reducing sleep to 0s
```

This is the result when the error popped back up, we clearly need rar2fs to limit the amount of opened files:
```
# lsof | grep rar2fs | wc -l
163689

```

**Comment by hasse69** [comment] 2020-01-08 21:28
Something is fishy here, how can you have 164k files opened if the limit was set to 65k?
Sure I can add logic to limit the number of worker threads, but then that would basically mean once the limit is hit it will become serialized due to busy-waits.

**Comment by hasse69** [comment] 2020-01-08 22:21
Try this patch too, it will make the directory walk calls non-recursive and open directories are closed during traversal. Scanning is still recursive but not the function calls since we now use a trampoline thread.

[issue131_2.patch.txt](https://github.com/hasse69/rar2fs/files/4037569/issue131_2.patch.txt)

**Comment by hasse69** [comment] 2020-01-08 23:43
Here is a new patch with a poor-mans throttling implementation.

[issue131_throttled_2.patch.txt](https://github.com/hasse69/rar2fs/files/4037847/issue131_throttled_2.patch.txt)

Some notes on this patch

* The warmup is turned off by default. To turn it on use the `-owarmup` mount option. The default number of "workers" started is 5. This can be controlled through the `-owarmup=n` syntax. A value of 0 will disable warmup. On my reference system the sweet spot was at a warmup value of 4 or 5 with an increased performance of ~100%. Value lower performed worse, higher values did not result in any improvement compared to the default. 
* The warmup will pound your CPU pretty badly. This is by design. The workers will take as much CPU as they possibly can but they will also yield for other tasks if needed.

**Comment by jcastilloalonso** [comment] 2020-01-09 01:06
Thanks Hans will check tonight when family goes to bed and report back. I
really appreciate all your work!

**Comment by hasse69** [comment] 2020-01-09 07:36
Here is a better version

[issue131_throttled_3.patch.txt](https://github.com/hasse69/rar2fs/files/4039186/issue131_throttled_3.patch.txt)

* Less CPU load
* Negative warmup values ignored
* Warmup only supported for folder mounts, for archive mounts the cache warmup does not really make much sense

**Comment by jcastilloalonso** [comment] 2020-01-09 18:51
Sorry for the delay, I decided to test in a little smaller mount I have so it could take less time to test. The throttle works perfectly, I just saw one rate limit and it was handled gracefully with no errors:

```
# rar2fs -f -owarmup -o allow_other,ro,umask=222,--seek-length=1 /mnt/Site2/ /mnt/unrar/Site2/
rar2fs[18525]: mounted /mnt/unrar/Site2
rar2fs[18525]: cache warmup initiated
rar2fs[18525]: cache warmup completed after 3120 seconds
```

I'm currently timing the ls -R method with time to see where we stand, will update when completed (so far over 2 hrs):

```
# rar2fs -o allow_other,ro,umask=222,--seek-length=1 /mnt/Site2/ /mnt/unrar/Site2/
# cd /mnt/unrar/Site2/
# time ls -R | wc -l
```

**Comment by hasse69** [comment] 2020-01-09 19:03
Sounds promising, at least no errors this time.
Some notes on your test above
* You do not need to add a separate `-owarmup`, you can simply add it to the list of your other mount options such as allow_other etc., like `-o allow_other,warmup,...`
* I do not think it is a fair comparison to pipe output from ls -R to wc -l and time it. I think a better command would be `# time ls -R >/dev/null`.

**Comment by jcastilloalonso** [comment] 2020-01-09 22:01
Thanks for the explanation, will surely do that.

Here is the result of the command, I did not stop and restart it as it takes just too long:

```
# time ls -R | wc -l
16277

real    329m16.104s
user    0m0.236s
sys     0m0.584s

```

So clearly the speedup is amazing. Also with backend directory warmup I don't experience the slow FUSE response I was getting with previous method (ls -R ) so it's a huge improvement in my use case.

Only thing that will be worht documenting is that users should only enable warmup in 1st lair and make sure it's deactivated in second, so it doesn't try to go folder by folder at the same time and choke the first lair with requests. Ideally subsequent lairs should hold less rar files making it easier to do on the fly.

Thanks again for this Hans. I will run the command now in background and report back if I run into any problems.

**Comment by hasse69** [comment] 2020-01-10 07:05
From what I can tell you got a rather remarkable performance boost.
I also did a quick test and I could not see any huge difference with or without using `wc -l` in the test.

>>> Only thing that will be worht documenting is that users should only enable warmup in 1st lair and make sure it's deactivated in second, so it doesn't try to go folder by folder at the same time and choke the first lair with requests.

Yes, it might be that using this feature on secondary stacks will defeat the purpose since it would basically result in a complete recursive file system travel towards the primary mount point and then less is gained. I say less because from my quick tests the results are not that bad really.

Without warmup on primary mount
```
rar2fs[8485]: cache warmup completed after 49 seconds
```
With warmup on primary mount
```
rar2fs[7676]: cache warmup completed after 26 seconds
```
With warmup on both primary and secondary mount 
```
rar2fs[14371]: cache warmup completed after 29 seconds
rar2fs[14421]: cache warmup completed after 31 seconds
```
So there is still a rather huge boost. But it would be worth mentioning in the man-page that optimal performance is not reached when used on stacks, agree.

**Comment by hasse69** [comment] 2020-01-11 23:05
Closing.

**Closed by hasse69** 2020-01-11 23:05 UTC
Labels: Enhancement, Priority-Medium
