### ISSUE TITLE
mkvs in rar archives with partXX names unplayable

### ISSUE THREAD

**Issue by magnub** [hasse69/rar2fs#77] opened 2017-06-17 21:34 UTC
Hi 

I'm unable to play mkvs inside archives with partXX.rar naming schemes with rar2fs 1.25.1
I can see the mkv file inside the archives but e.g. mpv and plex fails with playback with:
Failed to recognize file format.

archives with rXX naming have no issues

**Comment by hasse69** [comment] 2017-06-18 07:20
I need some more details about the archive since I cannot reproduce it myself.
Compressed or store mode? RAR4 or RAR5 format? Size of .mkv?

**Comment by hasse69** [comment] 2017-06-18 08:25
I have tested both a 1GiB and a 8GiB file split using 150MiB volume parts using new style archive (,partXX) and then performed a binary diff with the original file. I still do not see any problems so I really need some more input on this one.

**Comment by hasse69** [comment] 2017-06-18 14:00
Are you using --seek-length=1 by any chance? I think I can see an issue there...
As a workaround try to use --seek-length=2 instead. I will look deeper into why --seek-length=1 suddenly stopped working for new naming scheme.

**Comment by magnub** [comment] 2017-06-18 15:13
Sorry for not being able to answer earlier, yes I'm using - - seek-length=1 I'll switch to 2 for now then thanks.

**Comment by hasse69** [comment] 2017-06-18 16:57
There is now a patch release fixing the incorrect volume count logic , https://github.com/hasse69/rar2fs/releases/tag/v1.25.2.
Closing this.

**Closed by hasse69** 2017-06-18 16:57 UTC
Labels: Defect, Priority-High

**Comment by magnub** [comment] 2017-06-18 18:20
Thanks for this, works fine now!
