### ISSUE TITLE
Build error on Sierra 10.2

### ISSUE THREAD

**Issue by jvreeken** [hasse69/rar2fs#83] opened 2017-09-19 16:04 UTC
2 warnings and 1 error generated:

```
rar2fs.c:1019:9: warning: 'CLOCK_REALTIME' macro redefined [-Wmacro-redefined]
#define CLOCK_REALTIME 0
        ^
/usr/include/time.h:154:9: note: previous definition is here
#define CLOCK_REALTIME _CLOCK_REALTIME
        ^
rar2fs.c:1025:12: error: static declaration of 'clock_gettime' follows
      non-static declaration
static int clock_gettime(int clk_id, struct timespec *ts)
           ^
/usr/include/time.h:177:5: note: previous declaration is here
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
    ^
rar2fs.c:1844:25: warning: 'syscall' is deprecated: first deprecated in macOS
      10.12 - syscall(2) is unsupported; please switch to a supported interface.
      For SYS_kdebug_trace use kdebug_signpost(). [-Wdeprecated-declarations]
                        fdatasync(eofd->fd);      /* XXX needed!? */
                        ^
./platform.h:127:24: note: expanded from macro 'fdatasync'
# define fdatasync(fd) syscall(SYS_fdatasync, (fd))
                       ^
/usr/include/unistd.h:733:6: note: 'syscall' has been explicitly marked
      deprecated here
int      syscall(int, ...);
```

**Comment by hasse69** [comment] 2017-09-19 16:49
Thanks for the report! Will look into it. Unfortunately I do not have access to a Sierra based platform so I will most likely need to completely rely on you for testing.

**Comment by hasse69** [comment] 2017-09-19 20:51
Can you please check what is defined in the auto-generated file `config.h` with respect to `HAVE_UNISTD_H`? It should read something like:
```
/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1
```

Also, the `fdatasync` issue is related to this:
```
#ifdef HAVE_FDATASYNC
#ifdef __APPLE__
# include <sys/syscall.h>
# define fdatasync(fd) syscall(SYS_fdatasync, (fd))
#endif
#else
# define fdatasync(fd) fsync(fd)
#endif
```
It seems historically OSX supported `fdatasync` in the form of a syscall. But now they have changed their mind? It is actually hard for me to know how exactly to identify OSX platforms that now mark syscalls as deprecated (mostly because I do not have access to such a system), like Sierra now seems to do. Since the use of `fdatasync` in the code is questionable, a simple way out is to define it to `fsync` as done for other platforms not supporting `fdatasync`.

**Comment by hasse69** [comment] 2017-09-19 21:23
You can try this patch on master/HEAD to see if it works.

[patch-83-1.txt](https://github.com/hasse69/rar2fs/files/1315868/patch-83-1.txt)

**Comment by jvreeken** [comment] 2017-09-20 15:50
Thank you!
With your help I was able to get it to install!
there was only 1 warning generated this time :)

I opened /usr/include/unistd.h and found the _POSIX_TIMERS line which looked like this:
`#define _POSIX_TIMERS                   (-1)            /* [TMR] */`
I changed it to:
`#define _POSIX_TIMERS                   (1)            /* [TMR] */`

Then I cloned master and downloaded your patch-83-1.txt and applied it by changing the file name to patch-83-1.diff and then running
`git apply patch-83-1.diff`

Here are the steps I followed to install rar2fs on OSX Sierra:
Install X-code with developer tools:
`xcode-select --install`

Reboot into recovery mode to disable csrutil so that it could install to /usr/local/bin.
```
csrutil disable
reboot
```
Install homebrew:
`
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
`
Install autoconf using homebrew:
`
brew install autoconf
`
Install automake using homebrew:
`
brew install automake
`
Then I was able to follow the install instructions in the wiki

For your reference
Here is the output that displayed for me after running ./configure && make
```
checking build system type... x86_64-apple-darwin16.7.0
checking host system type... x86_64-apple-darwin16.7.0
checking target system type... x86_64-apple-darwin16.7.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... config/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether byte ordering is bigendian... no
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking malloc.h usability... no
checking malloc.h presence... no
checking for malloc.h... no
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking sys/file.h usability... yes
checking sys/file.h presence... yes
checking for sys/file.h... yes
checking sys/mount.h usability... yes
checking sys/mount.h presence... yes
checking for sys/mount.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/statvfs.h usability... yes
checking sys/statvfs.h presence... yes
checking for sys/statvfs.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking ucontext.h usability... no
checking ucontext.h presence... no
checking for ucontext.h... no
checking sched.h usability... yes
checking sched.h presence... yes
checking for sched.h... yes
checking sys/sysmacros.h usability... no
checking sys/sysmacros.h presence... no
checking for sys/sysmacros.h... no
checking sys/xattr.h usability... yes
checking sys/xattr.h presence... yes
checking for sys/xattr.h... yes
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for stdbool.h that conforms to C99... yes
checking for _Bool... no
checking whether to enable assertions... yes
checking for uid_t in sys/types.h... yes
checking for inline... inline
checking for mode_t... yes
checking for off_t... yes
checking for pid_t... yes
checking for size_t... (cached) yes
checking for ssize_t... yes
checking for struct stat.st_blksize... yes
checking for struct stat.st_gen... yes
checking for struct stat.st_atim... no
checking for struct stat.st_ctim... no
checking for struct stat.st_mtim... no
checking for struct stat.st_blocks... yes
checking for struct stat.st_rdev... yes
checking for uint64_t... yes
checking for a working PRIu64... yes
checking return type of signal handlers... void
checking for struct sigaction.sa_sigaction... yes
checking for unistd.h... (cached) yes
checking for working chown... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for _LARGEFILE_SOURCE value needed for large files... no
checking whether lstat correctly handles trailing slash... no
checking for mktime... yes
checking for atexit... yes
checking for dup3... no
checking for fs_stat_dev... no
checking for ftruncate... yes
checking for getcwd... yes
checking for getpass... yes
checking for lchown... yes
checking for memchr... yes
checking for memmove... yes
checking for memset... yes
checking for mkdir... yes
checking for realpath... yes
checking for rmdir... yes
checking for select... yes
checking for setlocale... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strpbrk... yes
checking for strrchr... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
checking for utimensat... no
checking for fdatasync... yes
checking for wcstombs... yes
checking for umask... yes
checking for library containing getxattr... none required
checking for getxattr... yes
checking for lgetxattr... no
checking for fgetxattr... yes
checking for listxattr... yes
checking for llistxattr... no
checking for flistxattr... yes
checking for removexattr... yes
checking for lremovexattr... no
checking for fremovexattr... yes
checking for setxattr... yes
checking for lsetxattr... no
checking for fsetxattr... yes
checking whether xattr interface takes additional options... yes
checking for fmemopen... no
checking for lockf... yes
checking for flock... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... (cached) yes
checking for getpagesize... yes
checking for working mmap... yes
checking for munmap... yes
checking for library containing backtrace... none required
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... -D_THREAD_SAFE
checking for PTHREAD_PRIO_INHERIT... yes
checking for main in -lrt... no
checking for main in -ldl... yes
checking fuse.h usability... yes
checking fuse.h presence... yes
checking for fuse.h... yes
checking for fuse_new in -lfuse4x... yes
checking for fuse_version... yes
checking for supported FUSE API version... yes
checking if we need to set -DCYGFUSE... no
checking how to run the C++ preprocessor... g++ -E
checking rar.hpp usability... yes
checking rar.hpp presence... yes
checking for rar.hpp... yes
checking for static linking of UnRAR library... fallback
checking for ./unrar/libunrar.a... yes
checking if unrar library needs -DRAR_SMP... yes
checking for iconv... yes
checking for working iconv... yes
checking how to link with libiconv... -liconv
checking for iconv declaration... 
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for commit hash in git repo... 38628b2
checking for sched_setaffinity... no
checking scandir ARG3 => const struct dirent * ... ok
checking if compiler supports -fno-omit-frame-pointer... yes
checking if compiler supports -Wextra... yes
checking if compiler supports -Wno-unused-result... yes
checking if compiler supports visibility attribute... yes
checking if linker supports -rdynamic... yes
checking for __sync_synchronize... yes
checking whether ln -s works... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: executing depfiles commands
/Library/Developer/CommandLineTools/usr/bin/make  all-am
g++ -DHAVE_CONFIG_H -I.  -I./unrar -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -DNDEBUG -DRARDLL -DRAR_SMP -Wall -Wno-reorder -g -O2 -D_THREAD_SAFE -pthread -MT dllext.o -MD -MP -MF .deps/dllext.Tpo -c -o dllext.o dllext.cpp
mv -f .deps/dllext.Tpo .deps/dllext.Po
gcc -DHAVE_CONFIG_H -I.  -I./unrar -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -DNDEBUG -Wall -fno-stack-protector -g -O2 -DGITREV_=0x38628b2 -fno-omit-frame-pointer -Wextra -Wno-unused-result -D_THREAD_SAFE -pthread -MT optdb.o -MD -MP -MF .deps/optdb.Tpo -c -o optdb.o optdb.c
mv -f .deps/optdb.Tpo .deps/optdb.Po
gcc -DHAVE_CONFIG_H -I.  -I./unrar -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -DNDEBUG -Wall -fno-stack-protector -g -O2 -DGITREV_=0x38628b2 -fno-omit-frame-pointer -Wextra -Wno-unused-result -D_THREAD_SAFE -pthread -MT filecache.o -MD -MP -MF .deps/filecache.Tpo -c -o filecache.o filecache.c
mv -f .deps/filecache.Tpo .deps/filecache.Po
gcc -DHAVE_CONFIG_H -I.  -I./unrar -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -DNDEBUG -Wall -fno-stack-protector -g -O2 -DGITREV_=0x38628b2 -fno-omit-frame-pointer -Wextra -Wno-unused-result -D_THREAD_SAFE -pthread -MT iobuffer.o -MD -MP -MF .deps/iobuffer.Tpo -c -o iobuffer.o iobuffer.c
mv -f .deps/iobuffer.Tpo .deps/iobuffer.Po
gcc -DHAVE_CONFIG_H -I.  -I./unrar -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -DNDEBUG -Wall -fno-stack-protector -g -O2 -DGITREV_=0x38628b2 -fno-omit-frame-pointer -Wextra -Wno-unused-result -D_THREAD_SAFE -pthread -MT sighandler.o -MD -MP -MF .deps/sighandler.Tpo -c -o sighandler.o sighandler.c
mv -f .deps/sighandler.Tpo .deps/sighandler.Po
gcc -DHAVE_CONFIG_H -I.  -I./unrar -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -DNDEBUG -Wall -fno-stack-protector -g -O2 -DGITREV_=0x38628b2 -fno-omit-frame-pointer -Wextra -Wno-unused-result -D_THREAD_SAFE -pthread -MT hashtable.o -MD -MP -MF .deps/hashtable.Tpo -c -o hashtable.o hashtable.c
mv -f .deps/hashtable.Tpo .deps/hashtable.Po
gcc -DHAVE_CONFIG_H -I.  -I./unrar -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -DNDEBUG -Wall -fno-stack-protector -g -O2 -DGITREV_=0x38628b2 -fno-omit-frame-pointer -Wextra -Wno-unused-result -D_THREAD_SAFE -pthread -MT dircache.o -MD -MP -MF .deps/dircache.Tpo -c -o dircache.o dircache.c
mv -f .deps/dircache.Tpo .deps/dircache.Po
gcc -DHAVE_CONFIG_H -I.  -I./unrar -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -DNDEBUG -Wall -fno-stack-protector -g -O2 -DGITREV_=0x38628b2 -fno-omit-frame-pointer -Wextra -Wno-unused-result -D_THREAD_SAFE -pthread -MT dirlist.o -MD -MP -MF .deps/dirlist.Tpo -c -o dirlist.o dirlist.c
mv -f .deps/dirlist.Tpo .deps/dirlist.Po
gcc -DHAVE_CONFIG_H -I.  -I./unrar -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -DNDEBUG -Wall -fno-stack-protector -g -O2 -DGITREV_=0x38628b2 -fno-omit-frame-pointer -Wextra -Wno-unused-result -D_THREAD_SAFE -pthread -MT rarconfig.o -MD -MP -MF .deps/rarconfig.Tpo -c -o rarconfig.o rarconfig.c
mv -f .deps/rarconfig.Tpo .deps/rarconfig.Po
gcc -DHAVE_CONFIG_H -I.  -I./unrar -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -DNDEBUG -Wall -fno-stack-protector -g -O2 -DGITREV_=0x38628b2 -fno-omit-frame-pointer -Wextra -Wno-unused-result -D_THREAD_SAFE -pthread -MT rar2fs.o -MD -MP -MF .deps/rar2fs.Tpo -c -o rar2fs.o rar2fs.c
rar2fs.c:1846:25: warning: implicit declaration of function 'fdatasync' is
      invalid in C99 [-Wimplicit-function-declaration]
                        fdatasync(eofd->fd);      /* XXX needed!? */
                        ^
1 warning generated.
mv -f .deps/rar2fs.Tpo .deps/rar2fs.Po
gcc -o rar2fs dllext.o optdb.o filecache.o iobuffer.o sighandler.o hashtable.o dircache.o dirlist.o rarconfig.o rar2fs.o -D_THREAD_SAFE -pthread -rdynamic    -lfuse4x ./unrar/libunrar.a -liconv -lstdc++ -ldl  
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
gcc -DHAVE_CONFIG_H -I.  -I./unrar -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -DNDEBUG -Wall -fno-stack-protector -g -O2 -DGITREV_=0x38628b2 -fno-omit-frame-pointer -Wextra -Wno-unused-result -D_THREAD_SAFE -pthread -MT mkr2i.o -MD -MP -MF .deps/mkr2i.Tpo -c -o mkr2i.o mkr2i.c
mv -f .deps/mkr2i.Tpo .deps/mkr2i.Po
gcc -o mkr2i mkr2i.o -rdynamic -ldl  
```
and then the output of running " sudo make install "
```
config/install-sh -c -d '/usr/local/bin'
  /usr/bin/install -c rar2fs mkr2i '/usr/local/bin'
/Library/Developer/CommandLineTools/usr/bin/make  install-exec-hook
make[2]: Nothing to be done for `install-exec-hook'.
 config/install-sh -c -d '/usr/local/share/man/man1'
 /usr/bin/install -c -m 644 rar2fs.1 '/usr/local/share/man/man1'
James-V:rar2fs jamesvreeken$ rar2fs
Usage: rar2fs source mountpoint [options]
Try `rar2fs -h' or `rar2fs --help' for more information.
```
I haven't tried mounting anything yet but it looks like it is installed now :)
Thank you so much for your help! 👍

**Comment by hasse69** [comment] 2017-09-21 07:32
The intention of patch is to make sure you do not need to update anything. You should never change system header files like that. That is asking for more trouble. Set back ` _POSIX_TIMERS` to what it was originally. It is however strange it is set to `-1` when the timer APIs are obviously available. I am not sure the comment about `TMR` could  be a hint this was supposed to be fixed later? You should check if you are using the latest system headers available.

The warning you still see is very odd! According to your configure run, fdatasync is available. It detects that by doing a compilation of a code segment so it is very unlikely configure got it wrong.

```
...
checking for fdatasync... yes
...
```

**Comment by hasse69** [comment] 2017-09-21 10:20
Btw, I must have stumbled into this problem before (but memory fails me), since if you look at the original code:
```
#ifdef HAVE_FDATASYNC
#ifdef __APPLE__
# include <sys/syscall.h>
# define fdatasync(fd) syscall(SYS_fdatasync, (fd))
#endif
#else
# define fdatasync(fd) fsync(fd)
#endif
```
It is obvious from this that when on `__APPLE__` based systems, even though `fdatasync`  is reported to be supported I changed it to a syscall instead? So what went on there? Maybe we should simply redefine it to `fsync` in this case? Maybe you can try that?

**Comment by hasse69** [comment] 2017-09-21 19:17
A bit of googling reveals similar issues with `fdatasync` reported by different project, it is defined but is missing a proper header prototype.
So we can add a prototype in `platform.h` in combination with a check in `configure.ac` to detect if a prototype for `fdatasync` is actually missing in `unistd.h`. Or simply revert to using `fsync` instead.

**Comment by hasse69** [comment] 2017-09-23 19:42
Lowering the priority on this since I am certain we have a solution.

**Comment by hasse69** [comment] 2017-10-11 18:12
Since I am not getting any feedback on this I will soon close this issue assuming the issue is resolved. If that is not the case please file a new issue.

**Closed** 2017-10-12 18:19 UTC
Labels: Defect, Priority-Low
