### ISSUE TITLE
Rar2fs not updating mount when rar files are still being added to folder

### ISSUE THREAD

**Issue by ntuts** [hasse69/rar2fs#116] opened 2019-10-22 11:20 UTC
Version info:
rar2fs v1.27.2-git8014672 (DLL version 8)    Copyright (C) 2009 Hans Beckerus
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under
certain conditions; see <http://www.gnu.org/licenses/> for details.
FUSE library version: 2.9.9
fusermount version: 2.9.9
using FUSE kernel interface version 7.19

In the past when I used rar2fs, I always moved my folders that contained rar files to the source of my rar2fs mount when all files were there. Now that I download or copy files to the source dir, I've noticed rar2fs doesn't update my mount once all the files have finished downloading or copying. Is this normal behaviour? Is there no way to invalidate the cache? The only way I can get the content from the rar archives to show up is by remounting the rar2fs mount, but that's no option since I'd have to stop my smbd services constantly to be able to unmount.

**Comment by hasse69** [comment] 2019-10-22 12:03
Thanks for the issue report.

First I need some clarification about what you mean when you say
> I always moved my folders that contained rar files to the source of my rar2fs mount

There is a rather big difference between moving archive to your source folder compared to your mount point. Since rar2fs does not actively monitor your source folder for updates (many reasons for this) the only way it can detect new archives is by copying them to the _mount point_. Regular files is not a problem since they are never put in the rar2fs internal cache. By copying to the mount point rar2fs gets notified by the kernel and can act accordingly and invalidate e.g. the folder cache.
An alternative (since copying to the rar2fs mounts is slower than copying to your source folder) is that you simply `touch` some file in the mount point folder you expect to find your new archive(s).
Please note that I have not tried this myself, but it should work, in theory at least.

If neither of these options are applicable (copying to the mount point instead of the source folder should in most cases) you can always flush the internal file and folder caches by sending a hang up signal (`kill -SIGHUP`) to the rar2fs main process.

**Comment by hasse69** [comment] 2019-10-22 17:13
And yea, that theory blew up since we are actually missing an invalidation call in the `utimens` callback.
Great, need to fix that...
Once fixed a simple touch of the folder (in the context of the mount point) will reveal anything new that has happened on source directory level since mount, e.g. a sequence like:
```
a) mount a on b
b) list b/foo (foo being a directory in a)
c) move some new archives to a/foo
d) list b/foo (no change)
e) touch b/foo
f) list b/foo and new contents should be visible
```
Note that this is *not* a recursive action, doing e.g `touch .` while standing in `b` would accomplish nothing if the new contents was added to `foo`.

**Comment by hasse69** [comment] 2019-10-24 08:34
There is in fact something else we could do here to have rar2fs detect when there are changes made somewhere in the source tree and force an invalidation of the cache.
This is actually something that has been on my mind for a rather long time, but I never had a chance to fully pursue it due to lack of time. Let me look into this again.

**Comment by hasse69** [comment] 2019-10-24 09:24
Try this patch on top of master/HEAD

[issue116.patch.txt](https://github.com/hasse69/rar2fs/files/3766697/issue116.patch.txt)

```
$ patch -p1 < issue116.patch.txt
```

**Comment by ntuts** [comment] 2019-10-24 18:41
Sorry for the lack of updates on my part, I will definitely give this a try
tomorrow, thanks!

**Comment by ntuts** [comment] 2019-10-25 07:21
Works great for me! Now while the rar files are copying, it will show them in the rar2fs mount and once everything has finished copying, it will only show the rar content, just like with any other folder that contains rars. Thanks!

**Comment by hasse69** [comment] 2019-10-25 07:40
Excellent. I will go through the patch again (the one I posted here was a quick try only) before I push it to master. We probably need to invalidate any possible file cache entries too in the case an archive is update to prevent stale cache information

**Comment by hasse69** [comment] 2019-10-25 22:52
Ok, this was a little bit more work than I expected, but please verify this new patch too.

[issue116.2.patch.txt](https://github.com/hasse69/rar2fs/files/3774083/issue116.2.patch.txt)

```
$ patch -p1 < issue116.patch.txt
```
You need to revert the previous patch before applying this one.

**Comment by hasse69** [comment] 2019-10-27 11:33
Just some status update. I am working on a "real" patch for this issue but it was definitely a lot more work than I anticipated and regression also takes time. I do not have an ETA right now. I will try to finish as soon as possible unless some other more prioritized task pops up.

**Comment by ntuts** [comment] 2019-10-28 09:17
Ok great, I'll definitely give it a try, thanks!

**Comment by hasse69** [comment] 2019-10-31 12:31
I have pushed f6225574d3365deb9a919db9154808bb092df943 to master.
I actually chose *not* to cover the few cases that directory modification time is not updated in this commit due to the additional complexity it introduces. I might return to this sometime later though.
Please test and report back.

**Comment by hasse69** [comment] 2019-11-03 23:10
Any news here?

**Comment by ntuts** [comment] 2019-11-04 15:07
Hi, I've just tested the latest build and everything works fine! I haven't tested this, so it's just a gut feeling, but it seems that this version has faster access times when opening a directory that contains archives, compared to the previously patched version. One thing I've noticed is that when you delete a rar file once everything is there, rar2fs keeps showing the content from the archive, even though it should no longer be accessible due to the missing rar.

**Comment by hasse69** [comment] 2019-11-04 17:06
> One thing I've noticed is that when you delete a rar file once everything is there, rar2fs keeps showing the content from the archive, even though it should no longer be accessible due to the missing rar.

That sounds weird? I just tried it myself and deleting a RAR file from a source folder will update the modification time of the parent directory and the cache is thus invalidated. After deletion the file it contained disappeared from the mount point side. Can you give some more details about how exactly you deleted your file(s).

**Comment by ntuts** [comment] 2019-11-04 17:35
So, my rar2fs is mounted as such:

sudo rar2fs /mnt/ext/X264 /mnt/plex/X264 -o allow_other --seek-length=1

I then created a new directory in /mnt/ext/X264 called "test" and started copying rar files to it. During the transfer, I was watching /mnt/plex/X264 and saw the .r00, .r01 etc. files appearying. After the transfer, it showed the content (an .mkv file). Next, I deleted a file (.r00) from the source directory with "rm -f", but the .mkv was still showing in the rar2fs mount. I also tried "touch -a source_dir" to see if that would trigger an update, but that had the same result.

**Comment by hasse69** [comment] 2019-11-04 17:46
Aha, ok. Then I understand. This is a scenario I am not really sure how to handle to be honest.
The problem is that the meta data found in the first volume file is enough to cache its contents.
Thus removing .r00 will not affect what is in fact presented. Extraction will not work obviously,

**Comment by zimme** [comment] 2019-11-04 17:58
Does the rar file metadata contain info about part files that could be used to validate their existence?

**Comment by hasse69** [comment] 2019-11-04 18:42
> Does the rar file metadata contain info about part files that could be used to validate their existence?

In some sense, yes. But the information is more on the level of being part of a volume or not and if current file is first, last or somewhere in between. We actually use this information already but in a different context.

Removal of files is a problem since the directory scanner is based on actual rather than "expected" contents. Thus, if you remove e.g. .r00, what will be scanned is .rar and then .r01 etc. We would need to rewrite the scanner completely to detect removal of files covered by the seek length. Files removed outside that of the seek length will still remain undetected. The only way to remedy such behavior would be to actually scan all headers and then the point of seek length is more or less lost completely. I will consider a rewrite of the scanner anyway since it has started to become a bit poisoned by covering all different corner cases. Feel free to file a new issue report for doing some improvements in this area. It is easier to follow up if we keep things separated.

**Comment by hasse69** [comment] 2019-11-05 09:36
I will close this issue now since I believe the actual problem that was reported has been solved and also to avoid this thread to derail completely. There will be reason to bring up this topic again for improvements in the area of archive validation and source folder updates.

**Closed by hasse69** 2019-11-05 09:36 UTC
Labels: Enhancement, Priority-Medium
